#!/usr/bin/env python3
"""1000体まで自動追加スクリプト"""

import re

APP_JS = '/home/takah/claude/company/anime_game_tools/app.js'

# radar: [行動力, 共感力, 社交性, 論理性, 責任感, 純粋さ]
NEW_CHARS = [
  # ── ワンピース追加 ──
  "{id:'nami_op',icon:'🍊',name:{ja:'ナミ',en:'Nami'},series:{ja:'ワンピース',en:'One Piece'},type:{ja:'航海士の切れ者 (ESTJ)',en:'Clever Navigator (ESTJ)'},profile:{E:3,T:4,S:3,J:4},desc:{ja:'航海術に長けた麦わらの仲間。お金と村への愛情が行動の原動力。怒ると怖いが仲間思いで頼りになる切れ者。',en:'Skilled navigator of the Straw Hats. Money and love for her village drive her. Scary when angry but reliable and caring for crewmates.'},traits:{ja:['航海士','切れ者','金好き','仲間思い','勇気'],en:['Navigator','Clever','Money-Lover','Loyal','Courageous']},radar:[65,72,78,85,82,50]}",
  "{id:'sanji_op',icon:'🍽️',name:{ja:'ヴィンスモーク・サンジ',en:'Vinsmoke Sanji'},series:{ja:'ワンピース',en:'One Piece'},type:{ja:'愛に生きるコック (ENFP)',en:'Cook Living for Love (ENFP)'},profile:{E:4,F:4,N:3,P:3},desc:{ja:'女性への愛と料理への情熱に生きるコック。蹴り技の達人で戦闘力は一流。ダメなとこもあるがいざとなれば仲間のために全力を尽くす。',en:'A cook living for love of women and passion for cooking. Master of kick techniques with top-tier combat. Has flaws but gives everything for crewmates when it counts.'},traits:{ja:['コック','情熱','女好き','義理','戦闘力'],en:['Cook','Passionate','Lady-Lover','Loyalty','Fighter']},radar:[80,75,82,60,78,55]}",
  "{id:'chopper_op',icon:'🦌',name:{ja:'トニートニー・チョッパー',en:'Tony Tony Chopper'},series:{ja:'ワンピース',en:'One Piece'},type:{ja:'天真爛漫な船医 (ENFP)',en:'Pure-Hearted Doctor (ENFP)'},profile:{E:3,F:4,N:2,P:4},desc:{ja:'ヒトヒトの実で人間の言葉を話せるトナカイ。船医として仲間の命を守る。素直で純粋、ほめられると調子に乗るのが愛らしい。',en:'A reindeer who ate the Human-Human Fruit and can speak human language. Protects crewmates as ship doctor. Straightforward and pure, adorably gets carried away when praised.'},traits:{ja:['純粋','船医','トナカイ','可愛い','勇気'],en:['Pure','Doctor','Reindeer','Cute','Brave']},radar:[55,85,72,70,88,95]}",
  "{id:'robin_op',icon:'📚',name:{ja:'ニコ・ロビン',en:'Nico Robin'},series:{ja:'ワンピース',en:'One Piece'},type:{ja:'静かな歴史家 (INTJ)',en:'Quiet Historian (INTJ)'},profile:{I:4,T:4,N:3,J:3},desc:{ja:'歴史の本文（ポーネグリフ）を読める考古学者。静かで冷静、黒い笑いが怖いが仲間を深く愛する。生きたいと叫んだシーンは屈指の名場面。',en:'An archaeologist who can read the Poneglyphs. Quiet and calm with a dark humor, but deeply loves her crew. Her cry of wanting to live is one of the series finest scenes.'},traits:{ja:['考古学者','冷静','知的','仲間愛','強さ'],en:['Archaeologist','Calm','Intellectual','Love for Crew','Strength']},radar:[70,78,45,90,80,60]}",
  "{id:'ace_op',icon:'🔥',name:{ja:'ポートガス・D・エース',en:'Portgas D. Ace'},series:{ja:'ワンピース',en:'One Piece'},type:{ja:'炎の兄 (ESFP)',en:'Flame Brother (ESFP)'},profile:{E:4,F:4,S:3,P:4},desc:{ja:'メラメラの実の能力者でルフィの兄。炎を自在に操る。仲間と弟を守るために命を懸ける義侠心の塊。白ひげを慕う姿が感動的。',en:'A Flame-Flame Fruit user and older brother of Luffy. Controls fire at will. A man of chivalry who risks his life to protect friends and his brother. His devotion to Whitebeard is moving.'},traits:{ja:['炎','兄','義侠心','白ひげ','カリスマ'],en:['Flame','Brother','Chivalry','Whitebeard','Charisma']},radar:[88,78,85,55,82,75]}",
  "{id:'shanks_op',icon:'⚔️',name:{ja:'赤髪のシャンクス',en:'Red-Haired Shanks'},series:{ja:'ワンピース',en:'One Piece'},type:{ja:'最強の海賊皇帝 (ENTJ)',en:'Greatest Emperor of the Sea (ENTJ)'},profile:{E:4,T:4,N:4,J:3},desc:{ja:'四皇の一人でルフィに麦わら帽子を渡した男。圧倒的な覇気と存在感で戦争を止めた実力者。飄々としているが決断は迅速かつ確実。',en:'One of the Four Emperors who gave Luffy his straw hat. Stopped a war with overwhelming Haki and presence. Easygoing but decisions are swift and certain.'},traits:{ja:['四皇','覇気','カリスマ','英雄','義理'],en:['Emperor','Haki','Charismatic','Heroic','Loyal']},radar:[95,65,78,82,88,60]}",
  "{id:'hancock_op',icon:'🐍',name:{ja:'ボア・ハンコック',en:'Boa Hancock'},series:{ja:'ワンピース',en:'One Piece'},type:{ja:'天下一美女の女帝 (ENTJ)',en:'Greatest Beauty Empress (ENTJ)'},profile:{E:3,T:4,N:3,J:4},desc:{ja:'アマゾン・リリーの女帝で九蛇の支配者。絶世の美女でルフィに一途な恋をする一面も。高慢だが仲間と愛する人には全てを捧げる。',en:'Empress of Amazon Lily and ruler of Kuja. Absolute beauty who falls single-mindedly in love with Luffy. Arrogant but gives everything for her people and the one she loves.'},traits:{ja:['女帝','美女','プライド','ルフィ愛','強さ'],en:['Empress','Beauty','Pride','Love for Luffy','Strength']},radar:[78,60,55,75,85,48]}",
  # ── 鬼滅の刃追加 ──
  "{id:'inosuke_kny',icon:'🐗',name:{ja:'嘴平伊之助',en:'Inosuke Hashibira'},series:{ja:'鬼滅の刃',en:'Demon Slayer'},type:{ja:'猪突猛進野生児 (ESTP)',en:'Wild Child Charging Ahead (ESTP)'},profile:{E:4,S:4,T:3,P:4},desc:{ja:'猪の頭をかぶった野生育ちの剣士。考えるより先に体が動く本能型。プライドが高いが炭治郎たちと共に成長していく。',en:'A sword-wielder raised in the wild wearing a boar head. Body moves before thinking, pure instinct type. High pride but grows alongside Tanjiro and the others.'},traits:{ja:['野生','本能','猪突','プライド','成長'],en:['Wild','Instinct','Charging','Pride','Growth']},radar:[88,40,55,35,60,78]}",
  "{id:'uzui_kny',icon:'💎',name:{ja:'宇髄天元',en:'Tengen Uzui'},series:{ja:'鬼滅の刃',en:'Demon Slayer'},type:{ja:'派手な音柱 (ESTP)',en:'Flamboyant Sound Hashira (ESTP)'},profile:{E:4,S:4,T:3,P:3},desc:{ja:'音の呼吸を使う派手好きな元忍の柱。「派手に行くぜ！」が口癖。妻3人への愛情と仲間への義理堅さが魅力。',en:'A Pillar who uses Sound Breathing, a flashy former ninja. Let's do this flashy! is his catchphrase. Charm lies in love for his three wives and loyalty to crewmates.'},traits:{ja:['派手','音柱','忍者','義理','愛妻家'],en:['Flamboyant','Sound Pillar','Ninja','Loyal','Devoted Husband']},radar:[82,60,85,55,75,65]}",
  "{id:'muichiro_kny',icon:'💨',name:{ja:'時透無一郎',en:'Muichiro Tokito'},series:{ja:'鬼滅の刃',en:'Demon Slayer'},type:{ja:'天才霞柱 (ISTP)',en:'Genius Mist Hashira (ISTP)'},profile:{I:4,S:3,T:4,P:3},desc:{ja:'霞の呼吸の使い手で最年少の柱。記憶を失い感情が薄かったが、仲間との交流で心を取り戻す。天才的な剣の才能を持つ。',en:'Mist Breathing user and youngest Pillar. Lost memories and had thin emotions but regains heart through bonds with allies. Has genius sword talent.'},traits:{ja:['天才','最年少','霞','記憶','感情'],en:['Genius','Youngest','Mist','Memory','Emotions']},radar:[85,45,35,70,75,58]}",
  "{id:'sanemi_kny',icon:'⚡',name:{ja:'不死川実弥',en:'Sanemi Shinazugawa'},series:{ja:'鬼滅の刃',en:'Demon Slayer'},type:{ja:'傷だらけの風柱 (ISTP)',en:'Scarred Wind Pillar (ISTP)'},profile:{I:3,T:4,S:4,J:4},desc:{ja:'風の呼吸の使い手。鬼への憎悪は人一倍強く粗野に見えるが、弟を思う涙が本当の姿。体中の傷は全て仲間を守った証。',en:'Wind Breathing user. Hatred for demons is stronger than anyone''s and appears rough, but tears for his brother show his true self. Every scar on his body proves protecting others.'},traits:{ja:['粗野','強さ','鬼憎悪','弟愛','傷'],en:['Rough','Strong','Demon Hatred','Brother Love','Scars']},radar:[90,48,40,65,85,42]}",
  "{id:'tomioka_kny',icon:'🌊',name:{ja:'冨岡義勇',en:'Giyu Tomioka'},series:{ja:'鬼滅の刃',en:'Demon Slayer'},type:{ja:'無口な水柱 (ISTJ)',en:'Silent Water Pillar (ISTJ)'},profile:{I:4,T:4,S:3,J:4},desc:{ja:'水の呼吸の使い手で口数が少ない。禰豆子を庇い炭治郎の可能性を見抜いた人物。感情を表に出さないが誰より深く人を思っている。',en:'Water Breathing user of few words. Protected Nezuko and saw Tanjiro''s potential. Doesn''t show emotions but thinks about people more deeply than anyone.'},traits:{ja:['無口','水柱','誠実','見極め','孤高'],en:['Silent','Water Pillar','Sincere','Discerning','Solitary']},radar:[88,52,28,72,90,55]}",
  # ── 呪術廻戦追加 ──
  "{id:'nobara_jjk',icon:'🔨',name:{ja:'釘崎野薔薇',en:'Nobara Kugisaki'},series:{ja:'呪術廻戦',en:'Jujutsu Kaisen'},type:{ja:'自分スタイルの術師 (ESTP)',en:'My-Style Sorcerer (ESTP)'},profile:{E:4,S:4,T:3,P:3},desc:{ja:'釘と藁人形を使う術師。自分のスタイルを曲げない強い信念と、都会への憧れを持つ田舎育ちの少女。強くてかっこよく可愛い。',en:'A sorcerer who uses nails and straw dolls. Has strong conviction in her style and rural upbringing with longing for the city. Strong, cool, and cute all at once.'},traits:{ja:['自分スタイル','田舎','強さ','オシャレ','根性'],en:['My-Style','Rural','Strong','Fashionable','Grit']},radar:[80,60,72,55,78,65]}",
  "{id:'yuta_jjk',icon:'💍',name:{ja:'乙骨憂太',en:'Yuta Okkotsu'},series:{ja:'呪術廻戦',en:'Jujutsu Kaisen'},type:{ja:'最強の特級術師 (INFJ)',en:'Strongest Special Grade (INFJ)'},profile:{I:4,N:4,F:4,J:3},desc:{ja:'リカへの愛と罪悪感を抱える特級術師。内向的で自信がなかったが、五条の指導のもと最強の術師に成長する。愛の力が呪力の源。',en:'A special grade sorcerer carrying love and guilt for Rika. Introverted and lacking confidence but grows into the strongest sorcerer under Gojo''s guidance. Love is the source of cursed energy.'},traits:{ja:['特級','愛','成長','罪悪感','最強'],en:['Special Grade','Love','Growth','Guilt','Strongest']},radar:[88,88,45,78,80,80]}",
  "{id:'geto_jjk',icon:'🌀',name:{ja:'夏油傑',en:'Suguru Geto'},series:{ja:'呪術廻戦',en:'Jujutsu Kaisen'},type:{ja:'理想を貫く反逆者 (INTJ)',en:'Idealist Rebel (INTJ)'},profile:{I:3,T:4,N:4,J:4},desc:{ja:'かつて五条の親友だった術師。非術師への絶望から理想の世界を作ろうとする。強い信念と知性を持つが、道を踏み外した悲劇の人物。',en:'Once Gojo''s best friend. Becomes disillusioned with non-sorcerers and tries to create an ideal world. Has strong conviction and intelligence but a tragic figure who strayed from his path.'},traits:{ja:['元親友','理想','反逆','知性','悲劇'],en:['Former Best Friend','Idealism','Rebellion','Intelligence','Tragedy']},radar:[75,42,55,88,82,38]}",
  # ── 僕のヒーローアカデミア追加 ──
  "{id:'uraraka_mha',icon:'🌸',name:{ja:'麗日お茶子',en:'Ochaco Uraraka'},series:{ja:'僕のヒーローアカデミア',en:'My Hero Academia'},type:{ja:'丸くて強い笑顔 (ESFJ)',en:'Round Strong Smile (ESFJ)'},profile:{E:4,F:4,S:3,J:3},desc:{ja:'浮かせるクセの能力者。家族を楽にしたいという夢のために戦う。明るく誰とでも仲良くなれるが、戦闘では思い切りの良さを見せる。',en:'Zero Gravity Quirk user. Fights with the dream of making life easier for her family. Bright and befriends anyone but shows decisiveness in combat.'},traits:{ja:['笑顔','家族愛','明るい','成長','友情'],en:['Smile','Family Love','Bright','Growth','Friendship']},radar:[65,88,88,55,72,90]}",
  "{id:'todoroki_mha',icon:'❄️',name:{ja:'轟焦凍',en:'Shoto Todoroki'},series:{ja:'僕のヒーローアカデミア',en:'My Hero Academia'},type:{ja:'氷炎の葛藤 (INFJ)',en:'Ice-Flame Conflict (INFJ)'},profile:{I:4,N:3,F:3,J:4},desc:{ja:'氷と炎を操る個性を持つ轟の息子。父への反発から左半身の炎を封印していたが、デクとの戦いで本当の自分を取り戻す。',en:'Son of Endeavor with a Quirk to control both ice and fire. Sealed his left fire side in defiance of his father, but regains his true self through battle with Deku.'},traits:{ja:['氷炎','葛藤','克服','父との確執','成長'],en:['Ice-Flame','Conflict','Overcoming','Father Issues','Growth']},radar:[90,55,38,72,78,55]}",
  "{id:'allmight_mha',icon:'💪',name:{ja:'オールマイト',en:'All Might'},series:{ja:'僕のヒーローアカデミア',en:'My Hero Academia'},type:{ja:'平和の象徴 (ENFJ)',en:'Symbol of Peace (ENFJ)'},profile:{E:4,F:4,N:3,J:4},desc:{ja:'平和の象徴でNo.1ヒーロー。デクにワン・フォー・オールを継承した師匠。常に笑顔で人々に希望を与え続ける存在。真のヒーロー。',en:'Symbol of Peace and No.1 Hero. The mentor who passed One For All to Deku. Always smiling and continuing to give people hope. A true hero.'},traits:{ja:['平和の象徴','希望','笑顔','師匠','No.1'],en:['Symbol of Peace','Hope','Smile','Mentor','No.1']},radar:[98,85,95,65,95,85]}",
  "{id:'aizawa_mha',icon:'😴',name:{ja:'相澤消太（イレイザーヘッド）',en:'Shota Aizawa (Eraserhead)'},series:{ja:'僕のヒーローアカデミア',en:'My Hero Academia'},type:{ja:'プロの教師 (ISTJ)',en:'Professional Teacher (ISTJ)'},profile:{I:4,T:4,S:3,J:4},desc:{ja:'個性を消すイレイザーヘッド。眠そうに見えるが学生への愛情が深いプロ教師。問題ある生徒も見捨てず引き上げる。',en:'Eraserhead who can erase Quirks. Appears sleepy but deeply loves his students as a professional teacher. Never abandons problematic students but lifts them up.'},traits:{ja:['プロ','教師','個性消去','厳格','愛情'],en:['Professional','Teacher','Quirk Erasure','Strict','Caring']},radar:[80,65,35,82,92,48]}",
  # ── 進撃の巨人追加 ──
  "{id:'armin_aot',icon:'📕',name:{ja:'アルミン・アルレルト',en:'Armin Arlert'},series:{ja:'進撃の巨人',en:'Attack on Titan'},type:{ja:'知略の天才 (INTP)',en:'Tactical Genius (INTP)'},profile:{I:3,T:4,N:4,P:3},desc:{ja:'体力はないが類稀な知性と戦略眼を持つ。仲間の命を守るために自らが「悪魔」になる決断ができる。夢を諦めない姿勢が心を打つ。',en:'Lacks physical strength but has extraordinary intellect and tactical vision. Can make the decision to become a devil to protect his friends'' lives. Never giving up on his dream is moving.'},traits:{ja:['知性','戦略','夢','勇気','友情'],en:['Intelligence','Strategy','Dream','Courage','Friendship']},radar:[45,78,55,95,72,78]}",
  "{id:'hange_aot',icon:'🔬',name:{ja:'ハンジ・ゾエ',en:'Hange Zoe'},series:{ja:'進撃の巨人',en:'Attack on Titan'},type:{ja:'巨人研究の熱狂者 (ENTP)',en:'Titan Research Enthusiast (ENTP)'},profile:{E:4,N:4,T:3,P:4},desc:{ja:'巨人への熱狂的な研究心を持つ調査兵団の指揮官。変わり者に見えるが、深い知性と仲間への愛情を持つ優れたリーダー。',en:'Commander of the Survey Corps with passionate dedication to Titan research. Appears eccentric but is an excellent leader with deep intellect and love for comrades.'},traits:{ja:['研究','情熱','奇人','知性','リーダー'],en:['Research','Passion','Eccentric','Intelligence','Leader']},radar:[72,72,78,88,75,65]}",
  "{id:'sasha_aot',icon:'🥩',name:{ja:'サシャ・ブラウス',en:'Sasha Blouse'},series:{ja:'進撃の巨人',en:'Attack on Titan'},type:{ja:'食いしん坊な戦士 (ESFP)',en:'Gluttonous Warrior (ESFP)'},profile:{E:4,S:4,F:3,P:4},desc:{ja:'食べることが大好きな調査兵団員。弓の腕前は一流で、戦場でも仲間を守るために奔走する。天真爛漫な笑顔で団員を和ませる存在。',en:'Survey Corps member who loves to eat. Top-class with a bow and runs to protect crewmates even in battle. Carefree smile that relaxes fellow soldiers.'},traits:{ja:['食いしん坊','弓','明るい','仲間思い','野性'],en:['Glutton','Bow','Bright','Loyal','Wild']},radar:[72,68,82,42,65,88]}",
  # ── HUNTER×HUNTER追加 ──
  "{id:'kurapika_hxh',icon:'🔗',name:{ja:'クラピカ',en:'Kurapika'},series:{ja:'HUNTER×HUNTER',en:'Hunter x Hunter'},type:{ja:'復讐に生きる賢者 (INTJ)',en:'Wise Man Living for Revenge (INTJ)'},profile:{I:4,T:4,N:4,J:4},desc:{ja:'クルタ族の生き残り。眷属の鎖の念能力で敵に迫る。冷静な判断力と強い意志の持ち主だが、復讐という目的が全てを支配する。',en:'Survivor of the Kurta clan. Pursues enemies with Chain Jail Nen ability. Has calm judgment and strong will but revenge as a goal controls everything.'},traits:{ja:['復讐','冷静','鎖','クルタ族','誓い'],en:['Revenge','Calm','Chain','Kurta Clan','Oath']},radar:[78,52,35,92,88,55]}",
  "{id:'leorio_hxh',icon:'🩺',name:{ja:'レオリオ・パラディナイト',en:'Leorio Paradinight'},series:{ja:'HUNTER×HUNTER',en:'Hunter x Hunter'},type:{ja:'熱血な医者の卵 (ESFJ)',en:'Hot-Blooded Aspiring Doctor (ESFJ)'},profile:{E:4,F:4,S:3,J:3},desc:{ja:'医者を目指す熱血漢。口は悪く見栄っ張りだが、友人のために泣ける純粋さがある。金のためと言いながら本当は人を救いたい正直者。',en:'Hot-blooded young man aiming to be a doctor. Crude mouth and boastful but has pure heart that cries for friends. Claims it''s for money but honestly wants to save people.'},traits:{ja:['熱血','医者','友情','口が悪い','純粋'],en:['Hot-Blooded','Doctor','Friendship','Crude','Pure']},radar:[70,82,78,55,65,75]}",
  "{id:'hisoka_hxh',icon:'🃏',name:{ja:'ヒソカ・モロウ',en:'Hisoka Morow'},series:{ja:'HUNTER×HUNTER',en:'Hunter x Hunter'},type:{ja:'戦闘狂の道化師 (ENTP)',en:'Battle-Crazed Jester (ENTP)'},profile:{E:3,T:4,N:4,P:4},desc:{ja:'戦闘を愛するマジシャンの殺し屋。強い相手との戦いに生を感じる危険な存在。ゴンとキルアを育て強くなるのを楽しみにしている。',en:'A magician assassin who loves combat. A dangerous existence that feels alive only in battle with strong opponents. Enjoys watching Gon and Killua grow stronger.'},traits:{ja:['戦闘狂','マジシャン','危険','興奮','奇妙'],en:['Battle-Crazed','Magician','Dangerous','Thrill','Bizarre']},radar:[90,28,55,85,32,28]}",
  "{id:'netero_hxh',icon:'🙏',name:{ja:'アイザック・ネテロ',en:'Isaac Netero'},series:{ja:'HUNTER×HUNTER',en:'Hunter x Hunter'},type:{ja:'最強の会長 (ENFJ)',en:'Strongest Chairman (ENFJ)'},profile:{E:3,F:3,N:4,J:4},desc:{ja:'ハンター協会会長で最強の念能力者の一人。強者との戦いを求める武人。キメラアント編での決死の戦いが伝説的。',en:'Hunter Association Chairman and one of the strongest Nen users. A warrior seeking battle with the strong. His desperate battle in the Chimera Ant arc is legendary.'},traits:{ja:['最強','会長','武人','決死','伝説'],en:['Strongest','Chairman','Warrior','Desperate','Legendary']},radar:[98,52,60,88,92,70]}",
  # ── NARUTO追加 ──
  "{id:'sasuke_naruto',icon:'⚡',name:{ja:'うちはサスケ',en:'Sasuke Uchiha'},series:{ja:'NARUTO -ナルト-',en:'Naruto'},type:{ja:'復讐と贖罪の天才 (INTJ)',en:'Genius of Revenge and Redemption (INTJ)'},profile:{I:4,T:4,N:4,J:4},desc:{ja:'うちは一族の生き残り。一族を滅ぼした兄への復讐を誓い修行を積む。孤高の天才だが、ナルトとの絆が最終的に彼を救う。',en:'Survivor of the Uchiha clan. Trains to avenge his brother who destroyed his clan. Solitary genius but his bond with Naruto ultimately saves him.'},traits:{ja:['天才','復讐','孤高','うちは','救済'],en:['Genius','Revenge','Solitary','Uchiha','Redemption']},radar:[92,42,28,90,75,40]}",
  "{id:'sakura_naruto',icon:'🌸',name:{ja:'春野サクラ',en:'Sakura Haruno'},series:{ja:'NARUTO -ナルト-',en:'Naruto'},type:{ja:'医療忍者の成長 (ESFJ)',en:'Medical Ninja Growth (ESFJ)'},profile:{E:3,F:4,S:3,J:4},desc:{ja:'内なるサクラという強い意志を持つ医療忍者。最初は弱かったが綱手の弟子として成長し、最強の医療忍者になる。',en:'Medical ninja with a strong inner will called Inner Sakura. Initially weak but grows as Tsunade''s disciple to become the strongest medical ninja.'},traits:{ja:['医療忍者','成長','強さ','仲間','綱手弟子'],en:['Medical Ninja','Growth','Strength','Comrades','Tsunade Disciple']},radar:[75,82,68,75,80,65]}",
  "{id:'kakashi_naruto',icon:'📖',name:{ja:'はたけカカシ',en:'Kakashi Hatake'},series:{ja:'NARUTO -ナルト-',en:'Naruto'},type:{ja:'コピー忍者の師匠 (ISTP)',en:'Copy Ninja Mentor (ISTP)'},profile:{I:3,T:4,S:3,J:3},desc:{ja:'千の忍術をコピーした写輪眼の使い手。飄々としているが実力は最高峰。チームをまとめ導く優れた師匠。',en:'Sharingan user who copied a thousand jutsu. Easygoing but top-tier in ability. An excellent mentor who guides and unifies his team.'},traits:{ja:['コピー忍者','写輪眼','師匠','飄々','実力者'],en:['Copy Ninja','Sharingan','Mentor','Easygoing','Skilled']},radar:[88,62,55,88,82,55]}",
  # ── SPY×FAMILY追加 ──
  "{id:'yor_spy',icon:'🌹',name:{ja:'ヨル・フォージャー',en:'Yor Forger'},series:{ja:'SPY×FAMILY',en:'SPY×FAMILY'},type:{ja:'殺し屋の優しい母 (ISFJ)',en:'Assassin Gentle Mother (ISFJ)'},profile:{I:3,F:4,S:4,J:3},desc:{ja:'茨姫という裏の顔を持つ凄腕の殺し屋だが、家族への愛情は本物。不器用だがアーニャとロイドのために全力を尽くす優しい人。',en:'A deadly assassin with the alias Thorn Princess but her love for family is genuine. Clumsy but gives everything for Anya and Loid. A gentle person.'},traits:{ja:['殺し屋','母','不器用','愛情','強さ'],en:['Assassin','Mother','Clumsy','Loving','Strong']},radar:[88,88,55,42,82,78]}",
  # ── ダンジョン飯追加 ──
  "{id:'marcille_dd',icon:'✨',name:{ja:'マルシル・ドノワ',en:'Marcille Donato'},series:{ja:'ダンジョン飯',en:'Delicious in Dungeon'},type:{ja:'魔法師のツッコミ役 (ENFP)',en:'Mage Straight-Man (ENFP)'},profile:{E:3,F:4,N:4,P:3},desc:{ja:'エルフの魔法師でライオスの妹の親友。モンスター料理への拒絶反応が激しいが、仲間のためなら頑張れる。長命種ゆえの孤独も抱える。',en:'Elven mage and best friend of Laios''s sister. Strong rejection of monster food but can push through for her friends. Also carries loneliness as a long-lived species.'},traits:{ja:['エルフ','魔法師','嫌がり屋','仲間思い','長命'],en:['Elf','Mage','Reluctant','Loyal','Long-Lived']},radar:[62,82,72,78,65,72]}",
  "{id:'chilchuck_dd',icon:'🔑',name:{ja:'チルチャック・ティムズ',en:'Chilchuck Tims'},series:{ja:'ダンジョン飯',en:'Delicious in Dungeon'},type:{ja:'罠師の現実主義 (ISTJ)',en:'Trap Master Realist (ISTJ)'},profile:{I:3,T:4,S:4,J:4},desc:{ja:'罠の解除のプロ。ハーフフットの罠師で常に現実的な視点を持つ。口は悪くドライだが、危険な場面では仲間の命を守るために力を発揮する。',en:'A professional at disarming traps. A Halfling trap specialist with a consistently practical perspective. Crude and dry but shows his worth protecting teammates in dangerous situations.'},traits:{ja:['罠師','現実主義','ハーフフット','プロ','仲間守護'],en:['Trap Master','Realist','Halfling','Professional','Protector']},radar:[55,48,38,82,88,42]}",
  # ── チェンソーマン追加 ──
  "{id:'power_csm',icon:'🩸',name:{ja:'パワー',en:'Power'},series:{ja:'チェンソーマン',en:'Chainsaw Man'},type:{ja:'血の悪魔の奔放さ (ESTP)',en:'Blood Devil Wildness (ESTP)'},profile:{E:4,S:4,T:3,P:4},desc:{ja:'血を操る悪魔でデンジの相棒。自己中心的で嘘つきだが、ニャーコへの愛情は本物。デンジとの友情を通じて成長する奔放な存在。',en:'Blood-manipulating devil and Denji''s partner. Self-centered liar but love for Meowy is genuine. A wild existence that grows through friendship with Denji.'},traits:{ja:['奔放','自己中','血','猫愛','成長'],en:['Wild','Self-Centered','Blood','Cat Love','Growth']},radar:[80,45,72,38,32,65]}",
  "{id:'makima_csm',icon:'👁️',name:{ja:'マキマ',en:'Makima'},series:{ja:'チェンソーマン',en:'Chainsaw Man'},type:{ja:'支配の悪魔 (INTJ)',en:'Control Devil (INTJ)'},profile:{I:4,T:4,N:4,J:4},desc:{ja:'公安のデビルハンターのリーダー。神秘的で謎めいた支配の悪魔。デンジに親切に接するが真の目的は深い闇の中にある。',en:'Leader of Public Safety Devil Hunters. Mysterious and enigmatic Control Devil. Acts kindly to Denji but true purpose lies in deep darkness.'},traits:{ja:['支配','神秘','謎','計画','闇'],en:['Control','Mysterious','Enigmatic','Plans','Darkness']},radar:[68,35,52,98,88,28]}",
  "{id:'aki_csm',icon:'⭐',name:{ja:'早川アキ',en:'Aki Hayakawa'},series:{ja:'チェンソーマン',en:'Chainsaw Man'},type:{ja:'義務感に生きる先輩 (ISTJ)',en:'Duty-Driven Senior (ISTJ)'},profile:{I:3,T:4,S:3,J:4},desc:{ja:'デビルハンターの先輩でデンジの指導役。家族をデビルに殺された過去を持つ。クールだが仲間への責任感が強い真面目な人物。',en:'Senior Devil Hunter and Denji''s mentor. Has past of family killed by devils. Cool but a serious person with strong sense of responsibility toward comrades.'},traits:{ja:['先輩','義務感','責任','過去','誠実'],en:['Senior','Duty','Responsibility','Past','Sincere']},radar:[75,62,45,72,90,52]}",
  # ── 鋼の錬金術師BROTHERHOOD追加 ──
  "{id:'alphonse_fma',icon:'🛡️',name:{ja:'アルフォンス・エルリック',en:'Alphonse Elric'},series:{ja:'鋼の錬金術師 BROTHERHOOD',en:'Fullmetal Alchemist: Brotherhood'},type:{ja:'鎧の中の優しい心 (INFJ)',en:'Gentle Heart in Armor (INFJ)'},profile:{I:3,F:4,N:3,J:4},desc:{ja:'体を失い鎧に魂を定着されたエドの弟。体がないのに誰より温かい心を持つ。兄とともに賢者の石を求め旅をする純粋な少年。',en:'Ed''s younger brother with soul bound to armor after losing his body. Has the warmest heart despite having no body. A pure boy journeying with his brother seeking the Philosopher''s Stone.'},traits:{ja:['優しい','兄弟愛','純粋','鎧','旅'],en:['Gentle','Brotherhood','Pure','Armor','Journey']},radar:[72,95,78,68,82,95]}",
  "{id:'mustang_fma',icon:'🔥',name:{ja:'ロイ・マスタング',en:'Roy Mustang'},series:{ja:'鋼の錬金術師 BROTHERHOOD',en:'Fullmetal Alchemist: Brotherhood'},type:{ja:'炎の錬金術師の野望 (ENTJ)',en:'Flame Alchemist Ambition (ENTJ)'},profile:{E:3,T:4,N:4,J:4},desc:{ja:'炎の錬金術師で大佐。国家錬金術師として軍上層部を目指す。飄々としているが確固たる目標と信念を持つカリスマリーダー。',en:'Flame Alchemist and Colonel. Aims for the top of the military as a State Alchemist. Easygoing but has firm goals and convictions as a charismatic leader.'},traits:{ja:['炎','野望','カリスマ','リーダー','信念'],en:['Flame','Ambition','Charismatic','Leader','Conviction']},radar:[80,55,65,90,85,42]}",
  "{id:'winry_fma',icon:'🔧',name:{ja:'ウィンリィ・ロックベル',en:'Winry Rockbell'},series:{ja:'鋼の錬金術師 BROTHERHOOD',en:'Fullmetal Alchemist: Brotherhood'},type:{ja:'機械鎧の天才職人 (ESFP)',en:'Genius Automail Mechanic (ESFP)'},profile:{E:4,F:4,S:4,P:3},desc:{ja:'オートメイルの天才技師でエドの幼馴染。エドとアルの旅を陰で支える存在。泣き虫だが芯は強く、大切な人への愛情を行動で示す。',en:'Genius automail engineer and Ed''s childhood friend. Supports Ed and Al''s journey from the shadows. Crybaby but has strong core, shows love for precious people through action.'},traits:{ja:['機械鎧','職人','幼馴染','愛情','成長'],en:['Automail','Mechanic','Childhood Friend','Loving','Growth']},radar:[65,88,78,62,72,82]}",
  # ── コードギアス追加 ──
  "{id:'suzaku_cg',icon:'🌸',name:{ja:'枢木スザク',en:'Suzaku Kururugi'},series:{ja:'コードギアス 反逆のルルーシュ',en:'Code Geass'},type:{ja:'正義の騎士の葛藤 (ISFJ)',en:'Knight of Justice Conflict (ISFJ)'},profile:{I:3,F:4,S:4,J:4},desc:{ja:'ルルーシュの幼なじみで正規軍の騎士。内部から変えるという信念を持つが、その正義が時に暴力的な手段を肯定してしまう葛藤を抱える。',en:'Lelouch''s childhood friend and knight of the regular military. Believes in changing things from within but struggles with his justice sometimes justifying violent means.'},traits:{ja:['正義','騎士','葛藤','幼馴染','矛盾'],en:['Justice','Knight','Conflict','Childhood Friend','Contradiction']},radar:[88,65,62,68,85,55]}",
  "{id:'cc_cg',icon:'🍕',name:{ja:'C.C.',en:'C.C.'},series:{ja:'コードギアス 反逆のルルーシュ',en:'Code Geass'},type:{ja:'不死の魔女 (INTP)',en:'Immortal Witch (INTP)'},profile:{I:4,T:4,N:4,P:3},desc:{ja:'ギアスを授ける不死の魔女。感情を表に出さず飄々としているが、ルルーシュとともに歩む存在。ピザへの愛情が唯一の人間らしさ。',en:'An immortal witch who grants Geass. Doesn''t show emotions and is easygoing but walks alongside Lelouch. Love of pizza is her only human quality.'},traits:{ja:['不死','魔女','飄々','ギアス','ピザ'],en:['Immortal','Witch','Easygoing','Geass','Pizza']},radar:[55,42,35,88,65,45]}",
  # ── ジョジョ追加 ──
  "{id:'giorno_jjba',icon:'🌟',name:{ja:'ジョルノ・ジョバァーナ',en:'Giorno Giovanna'},series:{ja:'ジョジョの奇妙な冒険 黄金の風',en:'JoJo\'s Bizarre Adventure: Golden Wind'},type:{ja:'黄金の精神 (INFJ)',en:'Golden Spirit (INFJ)'},profile:{I:3,N:4,F:3,J:4},desc:{ja:'ディオの息子でギャングスターを目指す少年。生物を創造するゴールド・エクスペリエンスの使い手。黄金の精神で悪に立ち向かう。',en:'Dio\'s son aiming to become a gangstar. User of Gold Experience which creates life. Confronts evil with the Golden Spirit.'},traits:{ja:['黄金','ギャング','信念','静けさ','父超え'],en:['Golden','Gangster','Conviction','Calm','Surpassing Father']},radar:[82,62,48,88,85,72]}",
  "{id:'jotaro_jjba',icon:'🎓',name:{ja:'空条承太郎',en:'Jotaro Kujo'},series:{ja:'ジョジョの奇妙な冒険',en:'JoJo\'s Bizarre Adventure'},type:{ja:'やれやれなスタンド使い (ISTP)',en:'Good Grief Stand User (ISTP)'},profile:{I:4,T:4,S:3,J:3},desc:{ja:'やれやれだぜが口癖のスタープラチナの使い手。クールで無口だが仲間と家族を守るためには命を懸ける。時間を止める能力が強力。',en:'Good grief is his catchphrase as user of Star Platinum. Cool and quiet but risks his life to protect friends and family. Ability to stop time is powerful.'},traits:{ja:['クール','やれやれ','スタープラチナ','強さ','家族愛'],en:['Cool','Good Grief','Star Platinum','Strong','Family Love']},radar:[95,48,32,82,88,45]}",
  "{id:'dio_jjba',icon:'🧛',name:{ja:'DIO',en:'DIO'},series:{ja:'ジョジョの奇妙な冒険',en:'JoJo\'s Bizarre Adventure'},type:{ja:'カリスマの悪 (ENTJ)',en:'Charismatic Evil (ENTJ)'},profile:{E:4,T:4,N:4,J:4},desc:{ja:'時間を止めるザ・ワールドの使い手。圧倒的なカリスマと野望で多くの者を従える。無駄無駄無駄の叫びが印象的。',en:'User of The World that stops time. Commands many with overwhelming charisma and ambition. His cry of Muda Muda Muda is iconic.'},traits:{ja:['悪','カリスマ','野望','吸血鬼','時間停止'],en:['Evil','Charismatic','Ambitious','Vampire','Time Stop']},radar:[88,28,78,88,72,28]}",
  # ── Re:ゼロ追加 ──
  "{id:'emilia_rezero',icon:'❄️',name:{ja:'エミリア',en:'Emilia'},series:{ja:'Re:ゼロから始める異世界生活',en:'Re:Zero'},type:{ja:'孤独な半エルフ王候補 (INFP)',en:'Lonely Half-Elf Candidate (INFP)'},profile:{I:3,F:4,N:3,P:3},desc:{ja:'精霊魔法を使う半エルフの王候補。外見からサテラの魔女と間違われ孤独に生きてきた。純粋で不器用な愛情表現が魅力。',en:'Half-elf royal candidate who uses spirit magic. Has lived in loneliness mistaken for the Witch of Envy due to appearance. Charm lies in pure and clumsy expression of love.'},traits:{ja:['純粋','半エルフ','孤独','精霊','不器用'],en:['Pure','Half-Elf','Lonely','Spirit','Clumsy']},radar:[60,88,55,65,72,90]}",
  "{id:'subaru_rezero',icon:'🏃',name:{ja:'菜月昂',en:'Subaru Natsuki'},series:{ja:'Re:ゼロから始める異世界生活',en:'Re:Zero'},type:{ja:'死に戻る諦めない男 (ENFP)',en:'Never-Giving-Up Return-by-Death Man (ENFP)'},profile:{E:4,F:4,N:3,P:3},desc:{ja:'死に戻る能力を持つ一般人。何度死んでも諦めず最善の未来を目指し続ける。精神的に追い詰められても立ち上がる強さが物語の核心。',en:'An ordinary person with the ability to Return by Death. Never gives up no matter how many times he dies, always pursuing the best future. The strength to rise even when mentally cornered is the story''s core.'},traits:{ja:['死に戻り','根性','諦めない','愛情','成長'],en:['Return by Death','Grit','Never Give Up','Love','Growth']},radar:[72,82,72,55,75,78]}",
  # ── 無職転生追加 ──
  "{id:'rudeus_mt',icon:'📚',name:{ja:'ルーデウス・グレイラット',en:'Rudeus Greyrat'},series:{ja:'無職転生 〜異世界行ったら本気だす〜',en:'Mushoku Tensei: Jobless Reincarnation'},type:{ja:'転生した本気の魔法使い (INTP)',en:'Reincarnated Serious Mage (INTP)'},profile:{I:4,T:4,N:4,P:3},desc:{ja:'前世の後悔を胸に異世界に転生した元引きこもり。赤ん坊から努力し続け世界最高峰の魔法使いになる。成長と贖罪の物語。',en:'Former shut-in reincarnated into another world carrying past regrets. Works hard from infancy to become one of the world''s greatest mages. A story of growth and redemption.'},traits:{ja:['転生','努力','魔法','贖罪','成長'],en:['Reincarnation','Effort','Magic','Redemption','Growth']},radar:[55,68,48,90,72,55]}",
  "{id:'eris_mt',icon:'🗡️',name:{ja:'エリス・ボレアス・グレイラット',en:'Eris Boreas Greyrat'},series:{ja:'無職転生 〜異世界行ったら本気だす〜',en:'Mushoku Tensei'},type:{ja:'猛烈な赤毛の騎士 (ESTP)',en:'Fierce Red-Haired Knight (ESTP)'},profile:{E:4,S:4,T:3,P:3},desc:{ja:'剣術を極めた赤毛の少女。激しい気性だが芯は優しく、ルーデウスに素直な感情を持てず苦しむ。成長して強くなった姿が感動的。',en:'A red-haired girl who has mastered swordsmanship. Fierce temperament but gentle at heart, struggling to express honest feelings toward Rudeus. Her growth into strength is moving.'},traits:{ja:['剣術','赤毛','激しい','優しい','成長'],en:['Swordsmanship','Red Hair','Fierce','Gentle','Growth']},radar:[85,55,55,48,68,65]}",
  # ── SPY×FAMILY ヨル以外追加 ──
  "{id:'damian_spy',icon:'👑',name:{ja:'デズモンド・ダミアン',en:'Damian Desmond'},series:{ja:'SPY×FAMILY',en:'SPY×FAMILY'},type:{ja:'プライドの裏の孤独 (ENTJ)',en:'Loneliness Behind Pride (ENTJ)'},profile:{E:3,T:4,N:3,J:4},desc:{ja:'著名な政治家の息子でイーデン校のエリート生徒。プライドが高くアーニャを敵視するが、実は父の愛情に飢えている孤独な少年。',en:'Son of a prominent politician and elite Eden student. High pride and rivals Anya but actually a lonely boy starved for his father\'s affection.'},traits:{ja:['エリート','プライド','孤独','父親','成長'],en:['Elite','Pride','Lonely','Father','Growth']},radar:[65,48,55,72,78,45]}",
  # ── ハイキュー追加 ──
  "{id:'hinata_hq',icon:'🏐',name:{ja:'日向翔陽',en:'Shoyo Hinata'},series:{ja:'ハイキュー!!',en:'Haikyu!!'},type:{ja:'小さな巨人 (ENFP)',en:'Little Giant (ENFP)'},profile:{E:4,F:3,N:3,P:4},desc:{ja:'身長は低いがバレーへの情熱は誰より大きい。瞬発力と運動神経で弱点を補い、チームを鼓舞する太陽のような存在。',en:'Short in stature but passion for volleyball is greater than anyone. Compensates for weaknesses with explosive speed and athleticism, a sunshine presence who inspires the team.'},traits:{ja:['小さい','情熱','跳躍力','太陽','諦めない'],en:['Short','Passionate','Jumping','Sunshine','Never Give Up']},radar:[78,72,88,42,65,90]}",
  "{id:'kageyama_hq2',icon:'🏐',name:{ja:'影山飛雄',en:'Tobio Kageyama'},series:{ja:'ハイキュー!!',en:'Haikyu!!'},type:{ja:'天才セッターの成長 (INTJ)',en:'Genius Setter Growth (INTJ)'},profile:{I:3,T:4,N:3,J:4},desc:{ja:'天才的なセットアップ技術を持つセッター。かつては独裁者と呼ばれたが、日向との関係で本当のバレーを学ぶ。',en:'A setter with genius setting skills. Once called a dictator but learns true volleyball through his relationship with Hinata.'},traits:{ja:['天才','セッター','成長','孤高','チームワーク'],en:['Genius','Setter','Growth','Solitary','Teamwork']},radar:[82,45,38,88,78,52]}",
  "{id:'oikawa_hq',icon:'🏐',name:{ja:'及川徹',en:'Toru Oikawa'},series:{ja:'ハイキュー!!',en:'Haikyu!!'},type:{ja:'努力の天才セッター (ENFJ)',en:'Hardworking Genius Setter (ENFJ)'},profile:{E:4,F:3,N:3,J:4},desc:{ja:'セッターとして天才ではないが誰より努力してきた男。チームをまとめるリーダーシップと個性を活かすセットで勝利を目指す。',en:'Not a genius setter but has worked harder than anyone. Aims for victory with leadership to unite the team and sets that bring out individuality.'},traits:{ja:['努力','リーダー','セッター','カリスマ','粘り強さ'],en:['Effort','Leader','Setter','Charisma','Persistence']},radar:[75,65,85,78,82,55]}",
  # ── 銀魂追加 ──
  "{id:'gintoki_gintama',icon:'🍭',name:{ja:'坂田銀時',en:'Gintoki Sakata'},series:{ja:'銀魂',en:'Gintama'},type:{ja:'だらしない侍の魂 (ENTP)',en:'Slacker Samurai Spirit (ENTP)'},profile:{E:3,N:4,T:3,P:4},desc:{ja:'週刊少年ジャンプが大好きなだらしない天然パーマ。普段は怠け者だが、いざとなれば圧倒的な剣の実力で仲間を守る。ギャグの中に泣ける展開を挟むのが銀魂の醍醐味。',en:'A shaggy-haired slacker who loves Shonen Jump. Usually lazy but when it counts, protects allies with overwhelming sword skills. The charm of Gintama is gut-wrenching scenes mixed into the comedy.'},traits:{ja:['ギャグ','侍','だらしない','実力者','友情'],en:['Comedy','Samurai','Slacker','Skilled','Friendship']},radar:[85,72,78,62,72,68]}",
  "{id:'kagura_gintama',icon:'☂️',name:{ja:'神楽',en:'Kagura'},series:{ja:'銀魂',en:'Gintama'},type:{ja:'天然パワー系女子 (ESTP)',en:'Natural Power Girl (ESTP)'},profile:{E:4,S:4,F:3,P:4},desc:{ja:'夜兎族の天才少女。圧倒的な怪力を持ちながら天真爛漫。チャイナドレスに傘を携えた姿が印象的。銀時・新八とともに万事屋を営む。',en:'A prodigy girl of the Yato clan. Has overwhelming strength while being carefree. Iconic image of Chinese dress and umbrella. Runs Yorozuya with Gintoki and Shinpachi.'},traits:{ja:['夜兎族','怪力','天真爛漫','食いしん坊','仲間'],en:['Yato Clan','Superstrength','Carefree','Glutton','Comrades']},radar:[90,65,85,38,58,85]}",
  # ── 名探偵コナン追加 ──
  "{id:'conan_dc',icon:'🔍',name:{ja:'江戸川コナン（工藤新一）',en:'Conan Edogawa (Shinichi Kudo)'},series:{ja:'名探偵コナン',en:'Detective Conan'},type:{ja:'小さな名探偵 (INTP)',en:'Little Great Detective (INTP)'},profile:{I:3,T:4,N:4,J:3},desc:{ja:'高校生探偵の工藤新一が薬で幼児化した名探偵。どんな複雑な謎も論理的に解き明かす天才。真実はいつも一つ！',en:'High school detective Shinichi Kudo, shrunken into a child by a drug. A genius who logically solves any complex mystery. There is always one truth!'},traits:{ja:['推理','天才','論理','真実','小学生'],en:['Deduction','Genius','Logic','Truth','Elementary Student']},radar:[45,58,62,98,80,72]}",
  # ── ドラゴンボール追加 ──
  "{id:'vegeta_db',icon:'👑',name:{ja:'ベジータ',en:'Vegeta'},series:{ja:'ドラゴンボール超',en:'Dragon Ball Super'},type:{ja:'プライドの王子 (INTJ)',en:'Prince of Pride (INTJ)'},profile:{I:3,T:4,N:3,J:4},desc:{ja:'サイヤ人の王子でプライドの塊。最強への執念でかつての敵から仲間へと変わる。孫悟空へのライバル心が成長の原動力。',en:'Saiyan prince and embodiment of pride. Changes from enemy to ally through obsession with being strongest. Rivalry with Son Goku is the driving force of growth.'},traits:{ja:['王子','プライド','ライバル','成長','最強'],en:['Prince','Pride','Rival','Growth','Strongest']},radar:[92,42,38,72,80,38]}",
  # ── SAO追加 ──
  "{id:'kirito_sao',icon:'🗡️',name:{ja:'桐ヶ谷和人（キリト）',en:'Kazuto Kirigaya (Kirito)'},series:{ja:'ソードアート・オンライン',en:'Sword Art Online'},type:{ja:'孤独なソードマスター (INTJ)',en:'Solitary Sword Master (INTJ)'},profile:{I:4,T:4,N:3,J:3},desc:{ja:'SAOのベータテスターでゲームの世界に閉じ込められた少年。デュアルブレードの使い手でソロプレイヤーとして最強を目指す。',en:'SAO beta tester who gets trapped in the game world. Dual blade wielder aiming to be the strongest as a solo player.'},traits:{ja:['ソロ','最強','デュアル','電脳世界','守護'],en:['Solo','Strongest','Dual Blade','Digital World','Protector']},radar:[90,55,38,78,78,52]}",
  "{id:'asuna_sao',icon:'⚡',name:{ja:'アスナ',en:'Asuna'},series:{ja:'ソードアート・オンライン',en:'Sword Art Online'},type:{ja:'電光石火の副団長 (ENFJ)',en:'Lightning-Fast Vice Commander (ENFJ)'},profile:{E:3,F:4,N:3,J:4},desc:{ja:'閃光のアスナと呼ばれる最強の剣士の一人。感情豊かで仲間想い、キリトへの愛情が最大の力の源。',en:'One of the strongest swordspeople called Lightning Asuna. Emotionally rich and caring for allies, love for Kirito is her greatest source of strength.'},traits:{ja:['閃光','副団長','愛','強さ','料理'],en:['Lightning','Vice Commander','Love','Strong','Cooking']},radar:[85,82,72,68,82,75]}",
  # ── その着せ替え人形 ──
  "{id:'marin_sono',icon:'🎎',name:{ja:'喜多川海夢',en:'Marin Kitagawa'},series:{ja:'その着せ替え人形は恋をする',en:'My Dress-Up Darling'},type:{ja:'ギャルオタクの輝き (ENFP)',en:'Gyaru Otaku Radiance (ENFP)'},profile:{E:4,F:4,N:4,P:4},desc:{ja:'人気ギャルだがオタクの趣味を隠さない明るい少女。五条に頼んでコスプレ衣装を作ってもらい、どんなキャラも完璧に演じる。',en:'A popular gyaru who doesn''t hide her otaku hobbies. A bright girl who asks Gojo to make cosplay costumes, performing any character perfectly.'},traits:{ja:['ギャル','オタク','コスプレ','明るい','自由'],en:['Gyaru','Otaku','Cosplay','Bright','Free']},radar:[78,82,92,52,58,88]}",
  "{id:'wakana_sono',icon:'🪆',name:{ja:'五条新菜',en:'Wakana Gojo'},series:{ja:'その着せ替え人形は恋をする',en:'My Dress-Up Darling'},type:{ja:'人形職人の不器用な誠実 (ISFP)',en:'Doll Artisan Clumsy Sincerity (ISFP)'},profile:{I:4,S:4,F:3,P:3},desc:{ja:'雛人形の頭師を目指す不器用な少年。海夢のコスプレ衣装を作ることで自分の世界が広がっていく。誠実で技術への真摯な姿勢が魅力。',en:'A clumsy boy aiming to be a hina doll craftsman. His world expands by making cosplay costumes for Marin. Charm lies in sincerity and serious attitude toward craft.'},traits:{ja:['職人','誠実','人形','不器用','成長'],en:['Craftsman','Sincere','Doll','Clumsy','Growth']},radar:[55,65,32,72,85,72]}",
  # ── かぐや様追加 ──
  "{id:'kaguya_klw',icon:'🎀',name:{ja:'四宮かぐや',en:'Kaguya Shinomiya'},series:{ja:'かぐや様は告らせたい',en:'Kaguya-sama: Love Is War'},type:{ja:'天才令嬢の恋愛脳 (INTJ)',en:'Genius Ojou Love Brain (INTJ)'},profile:{I:3,T:4,N:4,J:4},desc:{ja:'四宮財閥令嬢で天才だが恋愛では素直になれない。白銀に告白させようと策略を練るが、その都度恋心に負けてしまう可愛さが魅力。',en:'Shinomiya conglomerate heiress and genius but can''t be honest in love. Schemes to make Shirogane confess but keeps losing to her own heart, which is her charm.'},traits:{ja:['天才','令嬢','ツンデレ','策略','かわいい'],en:['Genius','Ojou','Tsundere','Scheming','Cute']},radar:[42,65,55,95,80,48]}",
  # ── ゆるキャン△ ──
  "{id:'nadeshiko_yc',icon:'🏕️',name:{ja:'各務原なでしこ',en:'Nadeshiko Kagamihara'},series:{ja:'ゆるキャン△',en:'Laid-Back Camp'},type:{ja:'キャンプ大好きの太陽 (ENFP)',en:'Sunshine Camp Lover (ENFP)'},profile:{E:4,F:4,S:3,P:4},desc:{ja:'キャンプに魅了された元気いっぱいの女の子。どこでも食欲旺盛で笑顔が絶えない。リンと共に各地でキャンプを楽しむ。',en:'A full-of-energy girl captivated by camping. Has big appetite and endless smiles anywhere. Enjoys camping across various locations with Rin.'},traits:{ja:['キャンプ','食欲','笑顔','元気','友情'],en:['Camping','Appetite','Smile','Energetic','Friendship']},radar:[65,82,88,45,62,92]}",
  "{id:'rin_yc',icon:'⛺',name:{ja:'志摩リン',en:'Rin Shima'},series:{ja:'ゆるキャン△',en:'Laid-Back Camp'},type:{ja:'ソロキャンの達人 (ISTP)',en:'Solo Camp Expert (ISTP)'},profile:{I:4,S:4,T:3,P:4},desc:{ja:'ソロキャンプを愛する静かな少女。自分のペースで自由にキャンプを楽しむことを好むが、なでしこと仲良くなる中で仲間との楽しさも知る。',en:'A quiet girl who loves solo camping. Prefers enjoying camping freely at her own pace but comes to know the joy of companions while befriending Nadeshiko.'},traits:{ja:['ソロ','静か','自由','マイペース','成長'],en:['Solo','Quiet','Free','Own Pace','Growth']},radar:[50,55,35,72,80,70]}",
  # ── けいおん！ ──
  "{id:'yui_keion',icon:'🎸',name:{ja:'平沢唯',en:'Yui Hirasawa'},series:{ja:'けいおん！',en:'K-On!'},type:{ja:'天才の空気系ギタリスト (ENFP)',en:'Genius Airhead Guitarist (ENFP)'},profile:{E:4,F:4,N:2,P:4},desc:{ja:'軽音部のギタリスト。天才的な演奏センスを持つが普段はボーっとしている。みんなに愛される天然キャラで部の雰囲気を作る。',en:'Guitarist of the Light Music Club. Has genius performance sense but usually spacey. A natural character loved by everyone who sets the club atmosphere.'},traits:{ja:['ギター','天然','天才','食いしん坊','笑顔'],en:['Guitar','Natural','Genius','Glutton','Smile']},radar:[72,85,90,35,42,95]}",
  # ── 僕の心のヤバイやつ ──
  "{id:'kyotaro_bokuyaba',icon:'🔪',name:{ja:'市川京太郎',en:'Kyotaro Ichikawa'},series:{ja:'僕の心のヤバイやつ',en:'The Dangers in My Heart'},type:{ja:'中二病の純愛少年 (INTJ)',en:'Chuunibyou Pure Love Boy (INTJ)'},profile:{I:4,T:3,N:4,J:3},desc:{ja:'中二病で暗い妄想を抱えるが、山田杏奈への純粋な恋心が彼を変えていく。不器用な純愛が微笑ましい成長ストーリー。',en:'Has chunibyo and dark delusions, but pure feelings for Anna Yamada change him. An endearing growth story of clumsy pure love.'},traits:{ja:['中二病','純愛','不器用','成長','妄想'],en:['Chunibyo','Pure Love','Clumsy','Growth','Delusions']},radar:[42,65,28,72,55,75]}",
  "{id:'anna_bokuyaba',icon:'📸',name:{ja:'山田杏奈',en:'Anna Yamada'},series:{ja:'僕の心のヤバイやつ',en:'The Dangers in My Heart'},type:{ja:'人気モデルの素顔 (ESFP)',en:'Popular Model True Face (ESFP)'},profile:{E:3,F:4,S:3,P:4},desc:{ja:'クラス一の人気者でモデルの少女。周囲には完璧に見えるが、市川の前では素の自分を出せる。食べることが大好きな可愛い一面も。',en:'The most popular class model. Appears perfect to others but can show her true self in front of Ichikawa. Also has a cute side of loving to eat.'},traits:{ja:['モデル','人気者','素の顔','食いしん坊','笑顔'],en:['Model','Popular','True Self','Foodie','Smile']},radar:[70,78,85,48,60,85]}",
  # ── ちはやふる ──
  "{id:'chihaya_cf',icon:'🃏',name:{ja:'綾瀬千早',en:'Chihaya Ayase'},series:{ja:'ちはやふる',en:'Chihayafuru'},type:{ja:'かるたの鬼 (ENFP)',en:'Karuta Demon (ENFP)'},profile:{E:4,N:4,F:3,P:4},desc:{ja:'かるたに全てを捧げる情熱的な少女。目標はクイーン位への挑戦と新との再会。一直線な情熱と仲間への愛が武器。',en:'A passionate girl who devotes everything to karuta. Goal is to challenge for the Queen position and reunite with Arata. Straight-line passion and love for friends are her weapons.'},traits:{ja:['かるた','情熱','一直線','青春','友情'],en:['Karuta','Passionate','Single-Minded','Youth','Friendship']},radar:[80,72,78,58,70,85]}",
  # ── からかい上手の高木さん ──
  "{id:'takagi_tkgk',icon:'😏',name:{ja:'高木さん',en:'Takagi'},series:{ja:'からかい上手の高木さん',en:'Teasing Master Takagi-san'},type:{ja:'完璧な恋のテイザー (ENFJ)',en:'Perfect Love Teaser (ENFJ)'},profile:{E:4,F:4,N:4,J:3},desc:{ja:'隣の席の西片くんをからかうことが大好きな少女。実は西片くんへの恋心を巧みに隠してからかいという形で表現する恋愛上手。',en:'A girl who loves teasing Nishikata-kun who sits next to her. Actually skillfully hides feelings for Nishikata and expresses them through teasing. Skilled in love.'},traits:{ja:['からかい','恋愛上手','笑顔','策略','純粋'],en:['Teasing','Love Expert','Smile','Scheming','Pure']},radar:[60,78,85,72,65,78]}",
  # ── ヴィンランド・サガ追加 ──
  "{id:'thorfinn_vs',icon:'⚔️',name:{ja:'トルフィン',en:'Thorfinn'},series:{ja:'ヴィンランド・サガ',en:'Vinland Saga'},type:{ja:'復讐から平和へ (INFP)',en:'From Revenge to Peace (INFP)'},profile:{I:4,N:4,F:4,P:3},desc:{ja:'父アシェラッドへの復讐に生きた少年が、真の戦士とは戦わない者と悟り平和を求める旅に変わる。壮大な成長の物語。',en:'A boy who lived for revenge against Askeladd transforms to pursue peace, realizing a true warrior is one who doesn''t fight. A grand story of growth.'},traits:{ja:['復讐','成長','平和','戦士','旅'],en:['Revenge','Growth','Peace','Warrior','Journey']},radar:[85,72,38,65,78,65]}",
  "{id:'askeladd_vs',icon:'⚔️',name:{ja:'アシェラッド',en:'Askeladd'},series:{ja:'ヴィンランド・サガ',en:'Vinland Saga'},type:{ja:'道化師の真の王 (ENTP)',en:'Jester''s True King (ENTP)'},profile:{E:3,T:4,N:4,P:3},desc:{ja:'ヴァイキングの傭兵隊長。飄々とした道化師の仮面の裏にウェールズへの愛国心と深謀を持つ。トルフィンの父を殺した宿敵でもある。',en:'Viking mercenary captain. Behind the mask of an easygoing jester lies Welsh patriotism and deep strategy. Also the mortal enemy who killed Thorfinn''s father.'},traits:{ja:['道化師','深謀','ウェールズ','裏切り','哲学'],en:['Jester','Deep Strategy','Wales','Betrayal','Philosophy']},radar:[75,38,62,92,62,30]}",
  # ── ブラッククローバー ──
  "{id:'asta_bc',icon:'⚔️',name:{ja:'アスタ',en:'Asta'},series:{ja:'ブラッククローバー',en:'Black Clover'},type:{ja:'魔力ゼロの魔法帝 (ENFP)',en:'Zero Magic Emperor (ENFP)'},profile:{E:4,F:4,S:4,P:3},desc:{ja:'魔力を持たない少年が魔法帝を目指す熱血ストーリー。反魔法の剣を使い叫び続ける姿がうるさいが愛される。',en:'Hot-blooded story of a boy with no magic aiming for Wizard King. Uses anti-magic swords and keeps yelling, which is annoying but beloved.'},traits:{ja:['魔力ゼロ','熱血','叫ぶ','諦めない','反魔法'],en:['Zero Magic','Hot-Blooded','Shouting','Never Give Up','Anti-Magic']},radar:[82,72,82,38,78,88]}",
  "{id:'yuno_bc',icon:'🌬️',name:{ja:'ユノ',en:'Yuno'},series:{ja:'ブラッククローバー',en:'Black Clover'},type:{ja:'天才の静けさ (INTJ)',en:'Genius Silence (INTJ)'},profile:{I:4,T:4,N:4,J:4},desc:{ja:'アスタの幼なじみで天才的な風魔法の使い手。クールで無駄口を叩かないが、アスタとのライバル関係が成長を加速させる。',en:'Asta\'s childhood friend and genius wind magic user. Cool without wasted words but rivalry with Asta accelerates growth.'},traits:{ja:['天才','風魔法','クール','ライバル','成長'],en:['Genius','Wind Magic','Cool','Rival','Growth']},radar:[88,40,32,85,82,52]}",
  # ── キングダム ──
  "{id:'shin_kingdom',icon:'⚔️',name:{ja:'信',en:'Shin'},series:{ja:'キングダム',en:'Kingdom'},type:{ja:'天下の大将軍を目指す (ENFP)',en:'Aiming for Greatest General (ENFP)'},profile:{E:4,F:4,N:3,P:4},desc:{ja:'奴隷から天下の大将軍を目指す少年兵。無謀に見えるほどの行動力と仲間への熱い想いで不可能を可能にし続ける。',en:'A young soldier aiming from slave to greatest general under heaven. Continues making the impossible possible with seemingly reckless drive and passionate feelings for comrades.'},traits:{ja:['熱血','将軍','成長','仲間','行動力'],en:['Hot-Blooded','General','Growth','Comrades','Drive']},radar:[88,72,78,42,72,85]}",
  "{id:'ouki_kingdom',icon:'🏹',name:{ja:'王騎',en:'Ouki'},series:{ja:'キングダム',en:'Kingdom'},type:{ja:'六大将軍の貫禄 (ENTJ)',en:'Six Generals Gravitas (ENTJ)'},profile:{E:3,T:4,N:4,J:4},desc:{ja:'秦国最強の六大将軍の一人。巨大な槍と圧倒的な戦場での存在感が印象的。信を認め育てようとした偉大な将軍。',en:'One of the strongest Six Great Generals of Qin. Impressive with his giant lance and overwhelming battlefield presence. A great general who recognized and tried to nurture Shin.'},traits:{ja:['六大将軍','貫禄','巨大な槍','戦場','指導'],en:['Six Generals','Gravitas','Giant Lance','Battlefield','Mentoring']},radar:[98,52,55,88,92,42]}",
  # ── 転スラ追加 ──
  "{id:'benimaru_tensura',icon:'🔥',name:{ja:'ベニマル',en:'Benimaru'},series:{ja:'転生したらスライムだった件',en:'That Time I Got Reincarnated as a Slime'},type:{ja:'炎の戦鬼のプライド (ISTP)',en:'Flame War Ogre Pride (ISTP)'},profile:{I:3,T:4,S:4,P:3},desc:{ja:'鬼族の戦士でリムルに忠誠を誓う。炎を操る実力者で戦闘の天才。寡黙で厳しいがリムルへの信頼は絶対的。',en:'Ogre warrior who pledges loyalty to Rimuru. A skilled flame wielder and combat genius. Taciturn and strict but absolute trust in Rimuru.'},traits:{ja:['炎','鬼族','プライド','強さ','忠義'],en:['Flame','Ogre','Pride','Strong','Loyalty']},radar:[90,42,38,72,82,45]}",
  "{id:'milim_tensura',icon:'👑',name:{ja:'ミリム・ナーヴァ',en:'Milim Nava'},series:{ja:'転生したらスライムだった件',en:'That Time I Got Reincarnated as a Slime'},type:{ja:'最古の魔王の天真爛漫 (ESFP)',en:'Oldest Demon Lord Carefree (ESFP)'},profile:{E:4,F:3,S:4,P:4},desc:{ja:'最古の魔王の一人で圧倒的な力を持つが子供のような純粋さを持つ。リムルをビーダイと呼んで懐き、友情と力の間で揺れる。',en:'One of the oldest Demon Lords with overwhelming power but childlike purity. Calls Rimuru Beady and takes to him, wavering between friendship and power.'},traits:{ja:['最古魔王','純粋','圧倒的力','子供らしさ','友情'],en:['Oldest Demon Lord','Pure','Overwhelming Power','Childlike','Friendship']},radar:[98,62,82,42,45,90]}",
  # ── 推しの子追加 ──
  "{id:'mem_oshinoko2',icon:'🎵',name:{ja:'MEMちょ',en:'MEM-cho'},series:{ja:'【推しの子】',en:'Oshi no Ko'},type:{ja:'実年齢隠しの配信者 (ENFP)',en:'Age-Hiding Streamer (ENFP)'},profile:{E:4,F:4,N:3,P:4},desc:{ja:'配信者として活躍する実は年上の少女。明るく八方美人だが根は努力家。推しの子の世界のキャラの中でも安心感ある存在。',en:'Actually an older girl active as a streamer. Bright and sociable but hardworking at heart. Among Oshi no Ko characters, a reassuring presence.'},traits:{ja:['配信者','明るい','年上','努力','可愛い'],en:['Streamer','Bright','Older','Hardworking','Cute']},radar:[72,75,88,48,62,78]}",
  # ── ブルーロック追加 ──
  "{id:'bachira_bl',icon:'⚽',name:{ja:'馬狼照英',en:'Reo Mikage'},series:{ja:'ブルーロック',en:'Blue Lock'},type:{ja:'超個人主義のストライカー (ESTP)',en:'Ultra-Individualist Striker (ESTP)'},profile:{E:4,S:4,T:4,P:4},desc:{ja:'自分のエゴを最大化することで最強のストライカーを目指す。攻撃的な個人主義が時に仲間との摩擦を生むが、その本能的な才能は本物。',en:'Aims to be the strongest striker by maximizing his own ego. Aggressive individualism sometimes creates friction with teammates but the instinctive talent is real.'},traits:{ja:['個人主義','エゴ','攻撃的','本能','才能'],en:['Individualist','Ego','Aggressive','Instinct','Talent']},radar:[88,32,55,62,45,65]}",
  "{id:'isagi_bl',icon:'⚽',name:{ja:'潔世一',en:'Yoichi Isagi'},series:{ja:'ブルーロック',en:'Blue Lock'},type:{ja:'空間を支配するストライカー (INTJ)',en:'Space-Controlling Striker (INTJ)'},profile:{I:3,T:4,N:4,J:4},desc:{ja:'空間認識能力に優れたストライカー。ゴールへの渇望と論理的な状況判断でブルーロックを勝ち上がる。成長するほど恐ろしい覚醒型。',en:'A striker with superior spatial recognition. Advances through Blue Lock with hunger for goals and logical situational judgment. An awakening type who becomes more fearsome as he grows.'},traits:{ja:['空間認識','渇望','成長','覚醒','論理'],en:['Spatial Recognition','Hunger','Growth','Awakening','Logic']},radar:[78,48,42,85,72,65]}",
  # ── 異修羅 ──
  "{id:'nilfloern_ishura',icon:'💀',name:{ja:'ニルフォルン',en:'Nilfhorun'},series:{ja:'異修羅',en:'Ishura'},type:{ja:'魔剣の孤独 (INFP)',en:'Demon Sword Solitude (INFP)'},profile:{I:4,N:4,F:3,P:3},desc:{ja:'強者のみが集う世界で最強を決める戦いに挑む剣士。孤独だが信念は揺るぎなく、弱者への優しさを秘める。',en:'A swordsman who challenges battles to determine the strongest in a world where only the strong gather. Solitary but with unshakeable conviction and hidden kindness to the weak.'},traits:{ja:['孤独','強さ','信念','剣','優しさ'],en:['Solitary','Strong','Conviction','Sword','Kindness']},radar:[90,52,28,78,72,58]}",
  # ── チ。追加 ──
  "{id:'novak_chi',icon:'🌍',name:{ja:'ノヴァク',en:'Novak'},series:{ja:'チ。-地球の運動について-',en:'Chi: About the Movement of Earth'},type:{ja:'信仰と科学の間で (INFJ)',en:'Between Faith and Science (INFJ)'},profile:{I:4,N:4,F:4,J:3},desc:{ja:'地動説を信じる者たちの後継者。信仰と真理の間で苦悩しながら、前の世代が命を懸けて守った知識を未来へ繋ごうとする。',en:'Successor to those who believed in heliocentrism. Struggles between faith and truth, trying to connect to the future the knowledge past generations protected with their lives.'},traits:{ja:['信仰','真理','継承','苦悩','覚悟'],en:['Faith','Truth','Inheritance','Struggle','Resolve']},radar:[42,80,45,82,78,72]}",
  # ── 正反対な君と僕 追加 ──
  "{id:'yamada_muki',icon:'📚',name:{ja:'山田くん',en:'Yamada-kun'},series:{ja:'正反対な君と僕',en:'You and I Are Polar Opposites'},type:{ja:'内気な優等生 (ISFP)',en:'Shy Honor Student (ISFP)'},profile:{I:4,S:3,F:3,P:3},desc:{ja:'真面目で内気な優等生。日野さんへの恋心を持ちながらも不器用な関係が続く。正反対な二人の関係が微笑ましい青春ラブコメ。',en:'A serious and shy honor student. Has feelings for Hino while their clumsy relationship continues. The relationship of polar opposites is an endearing youth rom-com.'},traits:{ja:['内気','優等生','真面目','不器用','青春'],en:['Shy','Honor Student','Serious','Clumsy','Youth']},radar:[42,58,28,78,82,72]}",
  # ── 逃げ上手の若君 追加 ──
  "{id:'yorishige_ys',icon:'🔮',name:{ja:'諏訪頼重',en:'Yorishige Suwa'},series:{ja:'逃げ上手の若君',en:'The Elusive Samurai'},type:{ja:'未来を見通す神官 (ENTP)',en:'Future-Seeing Priest (ENTP)'},profile:{E:4,T:3,N:4,P:4},desc:{ja:'諏訪の神官で未来を見通す力を持つ。時行に逃げることの才能を見出し守る存在。飄々とした態度の裏に深い愛情と覚悟がある。',en:'Suwa shrine priest with the power to foresee the future. Finds talent in Tokiyuki for fleeing and protects him. Behind his easygoing attitude lies deep love and resolve.'},traits:{ja:['予知','神官','飄々','愛情','覚悟'],en:['Precognition','Priest','Easygoing','Love','Resolve']},radar:[55,72,78,85,65,60]}",
  # ── SAKAMOTO DAYS 追加 ──
  "{id:'shin_sd',icon:'👓',name:{ja:'シン・アダム',en:'Shin Adar'},series:{ja:'SAKAMOTO DAYS',en:'Sakamoto Days'},type:{ja:'テレパシーの元殺し屋 (INFP)',en:'Telepathy Former Assassin (INFP)'},profile:{I:4,N:4,F:4,P:3},desc:{ja:'人の心が読めるテレパシー能力者の元殺し屋。坂本に出会い更生した繊細な青年。過去の罪と向き合いながら新しい生き方を模索する。',en:'A former assassin with telepathy who can read minds. A sensitive young man rehabilitated after meeting Sakamoto. Searching for a new way of life while facing past sins.'},traits:{ja:['テレパシー','繊細','更生','過去','成長'],en:['Telepathy','Sensitive','Rehabilitation','Past','Growth']},radar:[55,85,42,78,65,72]}",
  # ── 東京リベンジャーズ追加 ──
  "{id:'draken_tr',icon:'🐉',name:{ja:'龍宮寺堅（ドラケン）',en:'Ken Ryuguji (Draken)'},series:{ja:'東京卍リベンジャーズ',en:'Tokyo Revengers'},type:{ja:'竜の副総長 (ISTP)',en:'Dragon Vice Commander (ISTP)'},profile:{I:3,T:4,S:4,J:4},desc:{ja:'東京卍會の副総長でマイキーの親友。頭に龍の刺青が印象的。無口で厳しいが仲間思いで義理堅い。マイキーの暴走を止める理性の柱。',en:'Tokyo Manji Gang\'s vice commander and Mikey\'s best friend. Impressive dragon tattoo on his head. Quiet and strict but loyal and faithful to comrades. The pillar of reason that stops Mikey\'s rampage.'},traits:{ja:['龍','副総長','理性','義理','仲間'],en:['Dragon','Vice Commander','Reason','Loyalty','Comrades']},radar:[88,55,45,72,90,52]}",
  # ── モブサイコ100追加 ──
  "{id:'reigen_mp100',icon:'💫',name:{ja:'霊幻新隆',en:'Arataka Reigen'},series:{ja:'モブサイコ100',en:'Mob Psycho 100'},type:{ja:'詐欺師の本物の師匠 (ENTP)',en:'Fraudster True Master (ENTP)'},profile:{E:4,T:3,N:4,P:4},desc:{ja:'霊能力を持たない霊能コンサルタント。詐欺師だがモブへの愛情と人生訓は本物。いざとなれば自分の言葉で怪霊に立ち向かう胆力がある。',en:'A spiritual consultant with no actual spiritual powers. A con man but love for Mob and life lessons are genuine. Has the nerve to confront evil spirits with his own words when it counts.'},traits:{ja:['詐欺師','言葉','師匠','胆力','本物'],en:['Con Man','Words','Master','Nerve','Genuine']},radar:[55,68,88,52,58,48]}",
  # ── ノラガミ追加 ──
  "{id:'yato_noragami',icon:'🗡️',name:{ja:'ヤト',en:'Yato'},series:{ja:'ノラガミ',en:'Noragami'},type:{ja:'無名神の夢 (ENFP)',en:'Nameless God Dream (ENFP)'},profile:{E:4,N:4,F:4,P:4},desc:{ja:'神社を持たない流浪の神。5円でどんな願いでも叶えようとする。明るいが孤独で、ひとに認められ覚えてもらうことを望む存在。',en:'A wandering god without a shrine. Tries to grant any wish for 5 yen. Bright but lonely, a being who wishes to be recognized and remembered by people.'},traits:{ja:['流浪','5円','夢','孤独','成長'],en:['Wandering','5 Yen','Dream','Lonely','Growth']},radar:[72,72,75,48,42,68]}",
  # ── PSYCHO-PASS追加 ──
  "{id:'tsunemori_pp',icon:'🔫',name:{ja:'常守朱',en:'Akane Tsunemori'},series:{ja:'PSYCHO-PASS サイコパス',en:'Psycho-Pass'},type:{ja:'揺るぎない正義の監視官 (INFJ)',en:'Unshakeable Justice Inspector (INFJ)'},profile:{I:3,N:4,F:4,J:4},desc:{ja:'シビュラシステムと向き合いながら真の正義を問い続ける監視官。圧力にも屈しない信念と、人間への深い共感が武器。',en:'An Inspector who continues questioning true justice while confronting the Sibyl System. Conviction that doesn''t yield to pressure and deep empathy for people are her weapons.'},traits:{ja:['正義','信念','共感','監視官','シビュラ'],en:['Justice','Conviction','Empathy','Inspector','Sibyl']},radar:[62,88,62,80,88,78]}",
  "{id:'kogami_pp',icon:'🚬',name:{ja:'狡噛慎也',en:'Shinya Kogami'},series:{ja:'PSYCHO-PASS サイコパス',en:'Psycho-Pass'},type:{ja:'元監視官の追跡者 (ISTP)',en:'Former Inspector Hunter (ISTP)'},profile:{I:4,T:4,S:4,P:3},desc:{ja:'槙島への復讐を胸に潜伏する元監視官。鋭い直感と圧倒的な身体能力で獲物を追い詰める。常守との複雑な関係が物語を彩る。',en:'Former Inspector lurking with revenge against Makishima in his heart. Corners prey with sharp intuition and overwhelming physical ability. Complex relationship with Tsunemori colors the story.'},traits:{ja:['復讐','潜伏','直感','肉体','信念'],en:['Revenge','Undercover','Intuition','Physical','Conviction']},radar:[88,45,35,82,72,42]}",
  # ── まどかマギカ追加 ──
  "{id:'sayaka_mami_mg',icon:'🎻',name:{ja:'美樹さやか',en:'Sayaka Miki'},series:{ja:'魔法少女まどか☆マギカ',en:'Puella Magi Madoka Magica'},type:{ja:'正義の代償 (ENFJ)',en:'Price of Justice (ENFJ)'},profile:{E:4,F:4,N:3,J:3},desc:{ja:'正義の魔法少女を自称し仲間を守るために戦う少女。誰かを救いたいという純粋な思いが彼女の悲劇の始まりとなる。',en:'A girl who calls herself a justice magical girl and fights to protect allies. The pure desire to save someone becomes the beginning of her tragedy.'},traits:{ja:['正義','悲劇','純粋','愛','変容'],en:['Justice','Tragedy','Pure','Love','Transformation']},radar:[72,82,72,45,78,82]}",
  # ── ヴァイオレット追加 ──
  "{id:'gilbert_veg',icon:'✉️',name:{ja:'ギルベルト・ブーゲンビリア',en:'Gilbert Bougainvillea'},series:{ja:'ヴァイオレット・エヴァーガーデン',en:'Violet Evergarden'},type:{ja:'愛の言葉を残した少佐 (INFJ)',en:'Major Who Left Words of Love (INFJ)'},profile:{I:4,N:4,F:4,J:3},desc:{ja:'ヴァイオレットに「愛している」と残した少佐。戦場で彼女に生きることと人間性を教えた存在。その言葉の意味がヴァイオレットの旅の出発点。',en:'The Major who left I love you for Violet. Taught her to live and humanity on the battlefield. The meaning of those words is the starting point of Violet''s journey.'},traits:{ja:['愛','少佐','言葉','教師','謎'],en:['Love','Major','Words','Teacher','Mystery']},radar:[55,85,45,72,78,70]}",
  # ── シュタインズゲート追加 ──
  "{id:'okabe_sg',icon:'📱',name:{ja:'岡部倫太郎（鳳凰院凶真）',en:'Rintaro Okabe (Hououin Kyouma)'},series:{ja:'シュタインズ・ゲート',en:'Steins;Gate'},type:{ja:'中二病の天才科学者 (ENTP)',en:'Chunibyo Genius Scientist (ENTP)'},profile:{E:4,T:4,N:4,P:3},desc:{ja:'自称「狂気のマッドサイエンティスト」の大学生。タイムリープ実験で世界線を巡り、仲間を守るために何度も過去に戻る決意をする。',en:'A college student who calls himself a mad scientist of madness. Travels world lines through time leap experiments and resolves to return to the past repeatedly to protect friends.'},traits:{ja:['中二病','タイムリープ','科学','仲間','覚悟'],en:['Chunibyo','Time Leap','Science','Friends','Resolve']},radar:[65,78,78,90,75,52]}",
  "{id:'kurisu_sg',icon:'🔬',name:{ja:'牧瀬紅莉栖',en:'Kurisu Makise'},series:{ja:'シュタインズ・ゲート',en:'Steins;Gate'},type:{ja:'天才少女の科学者 (INTJ)',en:'Genius Girl Scientist (INTJ)'},profile:{I:3,T:4,N:4,J:4},desc:{ja:'18歳でありながら世界的な神経科学者。岡部のことをツンデレしながら共同研究を進める。論理と感情の間で揺れる人間らしい天才。',en:'An 18-year-old world-class neuroscientist. Progresses collaborative research while being tsundere toward Okabe. A human genius wavering between logic and emotion.'},traits:{ja:['天才','科学者','ツンデレ','論理','感情'],en:['Genius','Scientist','Tsundere','Logic','Emotion']},radar:[45,65,52,98,80,55]}",
  # ── 約束のネバーランド ──
  "{id:'emma_tpn',icon:'🌿',name:{ja:'エマ',en:'Emma'},series:{ja:'約束のネバーランド',en:'The Promised Neverland'},type:{ja:'誰も見捨てない主人公 (ENFP)',en:'Leave No One Behind Protagonist (ENFP)'},profile:{E:4,F:4,N:3,P:3},desc:{ja:'農園での真実を知り誰一人置いていかないという信念で仲間を導く少女。身体能力が高く感情豊か、強い意志で不可能を突破する。',en:'A girl who learns the truth of the farm and leads comrades with conviction to leave no one behind. High physical ability and emotionally rich, breaks through the impossible with strong will.'},traits:{ja:['諦めない','仲間','感情','強さ','知性'],en:['Never Give Up','Comrades','Emotional','Strong','Intelligent']},radar:[80,90,82,72,85,90]}",
  "{id:'norman_tpn',icon:'📊',name:{ja:'ノーマン',en:'Norman'},series:{ja:'約束のネバーランド',en:'The Promised Neverland'},type:{ja:'計算高い天才の愛 (INTJ)',en:'Calculating Genius Love (INTJ)'},profile:{I:3,T:4,N:4,J:4},desc:{ja:'農園で最高の点数を持つ天才。全ての計算の上に成り立つ戦略で仲間を守る。エマへの深い愛情が行動の根底にある。',en:'A genius with top scores at the farm. Protects comrades with strategy built on all calculations. Deep love for Emma is the foundation of his actions.'},traits:{ja:['天才','計算','愛情','戦略','守護'],en:['Genius','Calculation','Love','Strategy','Protection']},radar:[65,78,58,98,88,60]}",
  # ── Dr.STONE追加 ──
  "{id:'senku_stone',icon:'🧪',name:{ja:'石神千空',en:'Senku Ishigami'},series:{ja:'Dr.STONE',en:'Dr. Stone'},type:{ja:'10億パーセント科学者 (INTP)',en:'10 Billion Percent Scientist (INTP)'},profile:{I:4,T:4,N:4,P:3},desc:{ja:'「10億パーセント」が口癖の天才科学者。科学の力で石化した世界を復興させる。どんな状況も科学で解決する圧倒的な知性と行動力。',en:'A genius scientist whose catchphrase is 10 billion percent. Restores a petrified world with the power of science. Overwhelming intellect and drive to solve any situation with science.'},traits:{ja:['科学','天才','10億パーセント','復興','知識'],en:['Science','Genius','10 Billion Percent','Revival','Knowledge']},radar:[60,42,58,98,75,45]}",
  # ── 天元突破グレンラガン ──
  "{id:'simon_gl',icon:'🔩',name:{ja:'シモン',en:'Simon'},series:{ja:'天元突破グレンラガン',en:'Gurren Lagann'},type:{ja:'天を突く鑚 (INFP)',en:'Heaven-Piercing Drill (INFP)'},profile:{I:3,F:4,N:4,P:3},desc:{ja:'小さな鑚で岩盤を掘り続けた少年が宇宙規模の戦いへ成長する。カミナを失い一度は折れるが、仲間と信念で最強の螺旋王へ。',en:'A boy who kept drilling through rock with a small drill grows into a cosmic-scale battle. Breaks once after losing Kamina but becomes the strongest Spiral King with friends and conviction.'},traits:{ja:['鑚','成長','螺旋','諦めない','友情'],en:['Drill','Growth','Spiral','Never Give Up','Friendship']},radar:[72,75,55,65,78,85]}",
  "{id:'kamina_gl',icon:'🌟',name:{ja:'カミナ',en:'Kamina'},series:{ja:'天元突破グレンラガン',en:'Gurren Lagann'},type:{ja:'天元突破のカリスマ (ENFP)',en:'Heaven-Piercing Charisma (ENFP)'},profile:{E:4,F:4,N:4,P:4},desc:{ja:'「信じるな、俺を信じるお前を信じろ！」の名言で知られるグレンラガンの精神的柱。圧倒的なカリスマで仲間を鼓舞する伝説の存在。',en:'Known for the quote: Do not believe in me, believe in you who believes in me. The spiritual pillar of Gurren Lagann. A legendary being who inspires allies with overwhelming charisma.'},traits:{ja:['カリスマ','信念','熱血','伝説','鼓舞'],en:['Charismatic','Conviction','Hot-Blooded','Legendary','Inspiring']},radar:[78,85,95,42,78,82]}",
  # ── ちいかわ ──
  "{id:'chiikawa_char',icon:'🐾',name:{ja:'ちいかわ',en:'Chiikawa'},series:{ja:'ちいかわ',en:'Chiikawa'},type:{ja:'なんかかわいいやつ (ISFP)',en:'Something Small and Cute (ISFP)'},profile:{I:3,F:4,S:4,P:3},desc:{ja:'なんか小さくてかわいいやつ。いつも一生懸命で泣き虫だが仲間との絆は深い。日常の小さな幸せを大切にするほのぼのキャラクター。',en:'Something small and cute. Always works hard and is a crybaby but bonds with friends are deep. A heartwarming character who cherishes small everyday happiness.'},traits:{ja:['かわいい','一生懸命','泣き虫','仲間','日常'],en:['Cute','Hardworking','Crybaby','Friends','Everyday']},radar:[42,88,65,38,58,95]}",
  "{id:'hachiware_char',icon:'🌙',name:{ja:'ハチワレ',en:'Hachiware'},series:{ja:'ちいかわ',en:'Chiikawa'},type:{ja:'お歌が好きな仲間 (ENFP)',en:'Song-Loving Friend (ENFP)'},profile:{E:3,F:4,N:3,P:4},desc:{ja:'ちいかわの親友。お歌と踊りが大好きで明るい性格。ちいかわと一緒に試練を乗り越えながらも前向きに生きるマイペースキャラ。',en:'Chiikawa\'s best friend. Loves songs and dancing with a bright personality. A go-at-own-pace character who lives positively while overcoming trials with Chiikawa.'},traits:{ja:['歌','踊り','明るい','マイペース','友情'],en:['Song','Dance','Bright','Own Pace','Friendship']},radar:[55,78,75,42,55,88]}",
  # ── 違国日記 ──
  "{id:'makoto_ik',icon:'📝',name:{ja:'高代槙生',en:'Makoto Takashiro'},series:{ja:'違国日記',en:'A Stranger\'s Diary'},type:{ja:'無愛想な小説家の優しさ (INTJ)',en:'Unsociable Novelist Kindness (INTJ)'},profile:{I:4,T:4,N:4,J:3},desc:{ja:'不器用で無愛想だが姪の朝を引き取る小説家。感情表現が苦手で人づきあいを避けるが、大切な人への思いやりを密かに持つ大人。',en:'A clumsy unsociable novelist who takes in her niece Asa. Poor at expressing emotions and avoids socializing but secretly holds consideration for precious people.'},traits:{ja:['小説家','無愛想','不器用','優しさ','大人'],en:['Novelist','Unsociable','Clumsy','Kind','Adult']},radar:[38,68,25,82,72,52]}",
  # ── 義妹生活 ──
  "{id:'saki_gimai',icon:'📖',name:{ja:'綾瀬沙季',en:'Saki Ayase'},series:{ja:'義妹生活',en:'Gimai Seikatsu'},type:{ja:'義理の妹の自立心 (ISTJ)',en:'Stepsister Independence (ISTJ)'},profile:{I:4,S:4,T:4,J:4},desc:{ja:'義兄への依存を避けようと自立を心がける義理の妹。感情を表に出さず合理的だが、少しずつ心を開いていく成長が魅力。',en:'A stepsister who strives for independence to avoid depending on her stepbrother. Does not show emotions and is rational but her gradual opening up is charming.'},traits:{ja:['自立','義妹','合理的','成長','素直'],en:['Independence','Stepsister','Rational','Growth','Honest']},radar:[45,55,32,82,85,55]}",
  # ── 違国日記 朝 ──
  "{id:'asa_ik',icon:'🌱',name:{ja:'田汲朝',en:'Asa Tamekumi'},series:{ja:'違国日記',en:'A Stranger\'s Diary'},type:{ja:'悲しみの中の成長 (INFP)',en:'Growth in Grief (INFP)'},profile:{I:3,F:4,N:3,P:3},desc:{ja:'両親を事故で亡くし槙生叔母に引き取られた少女。戸惑いながらも新しい生活に適応し、自分の感情と向き合いながら成長する。',en:'A girl who lost her parents in an accident and was taken in by Aunt Makoto. Adapts to new life while bewildered and grows while confronting her own emotions.'},traits:{ja:['悲しみ','成長','適応','自分探し','素直'],en:['Grief','Growth','Adaptation','Self-Discovery','Honest']},radar:[45,82,55,52,58,80]}",
  # ── アオのハコ 追加 ──
  "{id:'hana_aono',icon:'🏀',name:{ja:'蜂須賀桃歌',en:'Momoka Hachisuka'},series:{ja:'アオのハコ',en:'Blue Box'},type:{ja:'バスケ女子の強さ (ISFP)',en:'Basketball Girl Strength (ISFP)'},profile:{I:3,S:4,F:4,P:3},desc:{ja:'バスケ部のエースで大喜多海の同居相手。天才的なスポーツ才能を持ちながら素直な感情表現が苦手。海への恋心に気づかない海に変化が生まれる。',en:'Basketball club ace and Taiki housemate. Has genius sports talent but struggles with honest emotional expression. Changes emerge as feelings grow.'},traits:{ja:['バスケ','天才','不器用','同居','成長'],en:['Basketball','Genius','Clumsy','Housemate','Growth']},radar:[78,68,55,62,72,70]}",
]

def fix_profile(char_str):
    """profileが不完全なものを修正"""
    return char_str

def build_insert():
    lines = []
    for char in NEW_CHARS:
        c = char.strip()
        # 末尾カンマを確保
        if not c.endswith(','):
            c += ','
        lines.append('  ' + c)
    return '\n'.join(lines)

def main():
    with open(APP_JS, 'r', encoding='utf-8') as f:
        content = f.read()

    # CHARACTERS配列の末尾 ]; を探す
    chars_start = content.index('const CHARACTERS = [')
    chars_end = content.index('];', chars_start)

    insert_text = '\n' + build_insert() + '\n'
    new_content = content[:chars_end] + insert_text + content[chars_end:]

    with open(APP_JS, 'w', encoding='utf-8') as f:
        f.write(new_content)

    # カウント確認
    char_section = new_content[chars_start:new_content.index('];', chars_start)]
    count = char_section.count("id:'")
    print(f"Characters after insert: {count}")

if __name__ == '__main__':
    main()
