// League of Legends Champion Data
// 全144チャンピオン基本情報

const CHAMPIONS = [
  // ===== TOP (33) =====
  {en:"Camille",jp:"カミール",role:"TOP",class:"ファイター/アサシン",diff:4,style:"精密な刃と脚部フックで敵を翻弄するサイバネティック戦士",img:"Camille"},
  {en:"Chogath",jp:"チョーガス",role:"TOP",class:"タンク/メイジ",diff:2,style:"沈黙と切断で敵を制し食べて成長するヴォイドの怪物",img:"Chogath"},
  {en:"Darius",jp:"ダリウス",role:"TOP",class:"ファイター",diff:2,style:"出血スタックとRの処刑でキルを量産するノクサスの手"},
  {en:"Fiora",jp:"フィオラ",role:"TOP",class:"ファイター/アサシン",diff:4,style:"急所を突いてHPを吸収し続ける最強デュエリスト"},
  {en:"Gangplank",jp:"ギャングプランク",role:"TOP",class:"ファイター/メイジ",diff:4,style:"樽爆発とグローバルRで試合全体を支配する海賊王"},
  {en:"Garen",jp:"ガレン",role:"TOP",class:"ファイター/タンク",diff:1,style:"自然回復と正義の裁きで初心者でも戦える騎士"},
  {en:"Gnar",jp:"グナー",role:"TOP",class:"ファイター/タンク",diff:3,style:"変身でミニとメガを使い分けるヤドカリ系フロントライン"},
  {en:"Gragas",jp:"グラガス",role:"TOP",class:"ファイター/タンク",diff:3,style:"樽と体当たりで前線を制圧する酔拳の巨漢"},
  {en:"Illaoi",jp:"イラオイ",role:"TOP",class:"ファイター",diff:2,style:"触手と霊魂でゾーンを支配する海神の巫女"},
  {en:"Irelia",jp:"イレリア",role:"TOP",class:"ファイター/アサシン",diff:4,style:"刃のダッシュとリセットで連続斬撃するイオニアの剣士"},
  {en:"Jax",jp:"ジャックス",role:"TOP",class:"ファイター/アサシン",diff:2,style:"1vs1最強クラスのランプポール使いの戦士"},
  {en:"Jayce",jp:"ジェイス",role:"TOP",class:"ファイター/メイジ",diff:4,style:"ハンマーと大砲を切り替えて近中距離を制する未来の守護者"},
  {en:"Kennen",jp:"ケネン",role:"TOP",class:"メイジ/ファイター",diff:3,style:"電気スタックとRの嵐でADCをシャットダウンするニンジャ"},
  {en:"Malphite",jp:"マルファイト",role:"TOP",class:"タンク",diff:1,style:"岩のような耐久とRのノックアップで集団戦を制する"},
  {en:"Mordekaiser",jp:"モルデカイザー",role:"TOP",class:"ファイター/メイジ",diff:2,style:"死の領域に引き込む1v1特化の鉄の支配者"},
  {en:"Nasus",jp:"ナサス",role:"TOP",class:"ファイター/タンク",diff:2,style:"Qスタックを溜め続けて後半無限に成長するジャッカル神"},
  {en:"Ornn",jp:"オルン",role:"TOP",class:"ファイター/タンク",diff:2,style:"フィールドでアイテムを作成し味方のアイテムを強化する鍛冶神"},
  {en:"Quinn",jp:"クイン",role:"TOP",class:"マークスマン/アサシン",diff:3,style:"鷹ヴァローを使ったブラインドと高機動で翻弄する"},
  {en:"Renekton",jp:"レネクトン",role:"TOP",class:"ファイター/タンク",diff:2,style:"怒りゲージとダッシュで序盤を制圧するワニの神"},
  {en:"Riven",jp:"リヴェン",role:"TOP",class:"ファイター/アサシン",diff:4,style:"QQQコンボと武器の解放で圧倒的なバーストを叩き込む剣士"},
  {en:"Sett",jp:"セット",role:"TOP",class:"ファイター",diff:2,style:"体力を力に変えてW一撃でど真ん中に叩き込むボス"},
  {en:"Shen",jp:"シェン",role:"TOP",class:"タンク",diff:2,style:"グローバルRで味方を守るシールドを持つニンジャタンク"},
  {en:"Singed",jp:"シンジド",role:"TOP",class:"タンク/メイジ",diff:2,style:"毒ガスを引きながら追いかけてくる狂気の錬金術師"},
  {en:"Sion",jp:"サイオン",role:"TOP",class:"タンク/ファイター",diff:2,style:"Rでマップを突進する巨大アンデッドタンク"},
  {en:"TahmKench",jp:"タムケンチ",role:"TOP",class:"タンク/サポート",diff:2,style:"味方を丸呑みして守るか敵を飲み込む大型ナマズ",img:"TahmKench"},
  {en:"Teemo",jp:"ティーモ",role:"TOP",class:"マークスマン/メイジ",diff:3,style:"キノコトラップとブラインドで全レーナーを悩ませる"},
  {en:"Trundle",jp:"トランドル",role:"TOP",class:"ファイター/タンク",diff:2,style:"敵の防御と体力を盗むトロールの王"},
  {en:"Tryndamere",jp:"トリンダメア",role:"TOP",class:"ファイター/アサシン",diff:3,style:"R無敵で死ねないクリティカル特化の野蛮な戦士"},
  {en:"Urgot",jp:"アーゴット",role:"TOP",class:"ファイター/タンク",diff:2,style:"脚部チェーンソーと処刑Rで敵を機械的に仕留める"},
  {en:"Vladimir",jp:"ウラジミール",role:"TOP",class:"メイジ/ファイター",diff:3,style:"血を操る吸血メイジ。後半に向けて際限なくスケールする"},
  {en:"Volibear",jp:"ヴォリベア",role:"TOP",class:"ファイター/タンク",diff:2,style:"雷の神として突進とかみつきで前線を支配するクマ神"},
  {en:"Yorick",jp:"ヨリック",role:"TOP",class:"ファイター",diff:2,style:"亡霊を使ってスプリットプッシュする墓掘り人"},
  {en:"Yone",jp:"ヨネ",role:"TOP",class:"ファイター/アサシン",diff:3,style:"魂を抜いて突進するアザカナの刃使いの剣客"},

  // ===== JUNGLE (34) =====
  {en:"Amumu",jp:"アムム",role:"JG",class:"タンク/メイジ",diff:1,style:"涙とバンデージで敵をルートするアンデッドの子供"},
  {en:"Diana",jp:"ダイアナ",role:"JG",class:"アサシン/ファイター",diff:2,style:"月光スタックとRのリセットで連続突撃する月の女神"},
  {en:"Ekko",jp:"エコー",role:"JG",class:"アサシン/ファイター",diff:3,style:"時間を戻すR無敵で奇襲して逃げる時間操作の天才"},
  {en:"Elise",jp:"エリス",role:"JG",class:"メイジ/アサシン",diff:4,style:"人間と蜘蛛の変身を活かす序盤最強ジャングラー"},
  {en:"Evelynn",jp:"イヴリン",role:"JG",class:"メイジ/アサシン",diff:4,style:"ステルスで忍び寄り甘い囁きで魅了するアサシン"},
  {en:"FiddleSticks",jp:"フィドルスティックス",role:"JG",class:"メイジ/サポート",diff:2,style:"Rで茂みから飛び出す究極のジャングル奇襲"},
  {en:"Graves",jp:"グレイブス",role:"JG",class:"ファイター/マークスマン",diff:2,style:"散弾銃と煙幕で近中距離を制圧するガンスリンガー"},
  {en:"Hecarim",jp:"ヘカリム",role:"JG",class:"ファイター/タンク",diff:2,style:"移動速度をダメージに変換して突撃する死の馬"},
  {en:"Ivern",jp:"アイヴァーン",role:"JG",class:"サポート",diff:4,style:"木のジャングラー。モンスターを解放しながら仲間を支援"},
  {en:"JarvanIV",jp:"ジャーヴァンⅣ",role:"JG",class:"ファイター/タンク",diff:2,style:"EQコンボのノックアップとフラッグ&ドラッグで戦場を支配",img:"JarvanIV"},
  {en:"Kayn",jp:"ケイン",role:"JG",class:"アサシン/ファイター",diff:2,style:"壁を通り抜け二つの形態から選択するシャドウアサシン"},
  {en:"Khazix",jp:"カジックス",role:"JG",class:"アサシン",diff:3,style:"孤立した敵を処刑する進化するヴォイドバグ",img:"Khazix"},
  {en:"Kindred",jp:"キンドレッド",role:"JG",class:"マークスマン/ファイター",diff:3,style:"スタックで成長し全員を無敵にするRを持つ死の使者"},
  {en:"LeeSin",jp:"リー・シン",role:"JG",class:"ファイター/アサシン",diff:5,style:"QQと壁蹴りインセクを使いこなすブラインドモンク",img:"LeeSin"},
  {en:"MasterYi",jp:"マスター・イー",role:"JG",class:"アサシン/ファイター",diff:2,style:"Rの無敵と高ASで敵を次々刈り取る一点突破の剣士",img:"MasterYi"},
  {en:"Nidalee",jp:"ニダリー",role:"JG",class:"メイジ/アサシン",diff:5,style:"槍を当てたら変身してジャンプで狩る高難度ハンター"},
  {en:"Nocturne",jp:"ノクターン",role:"JG",class:"アサシン/ファイター",diff:2,style:"RでマップをブラックアウトしてDash Gankする悪夢"},
  {en:"Nunu",jp:"ヌヌ",role:"JG",class:"タンク/ファイター",diff:1,style:"雪玉Rでチームを楽しませながらオブジェクトを制圧",img:"Nunu"},
  {en:"Rammus",jp:"ラムス",role:"JG",class:"タンク",diff:1,style:"物理防御を反射し転がるだけで敵を倒すタートル"},
  {en:"RekSai",jp:"レク・サイ",role:"JG",class:"ファイター/タンク",diff:2,style:"穴を掘って地下移動するトンネルジャングラー",img:"RekSai"},
  {en:"Rengar",jp:"レンガー",role:"JG",class:"アサシン/ファイター",diff:4,style:"茂みからジャンプして瞬殺するライオンのアサシン"},
  {en:"Sejuani",jp:"セジュアニ",role:"JG",class:"タンク",diff:1,style:"猪を乗りこなし氷のCC連打でチームのフロントラインを担う"},
  {en:"Shaco",jp:"シャコ",role:"JG",class:"アサシン",diff:4,style:"ジョーカー的奇術で騙し続ける究極のトリックスター"},
  {en:"Shyvana",jp:"シヴァーナ",role:"JG",class:"ファイター/タンク",diff:2,style:"ドラゴンに変身してAOEダメージを振りまく炎の女"},
  {en:"Udyr",jp:"ウディア",role:"JG",class:"ファイター/タンク",diff:3,style:"4種のスタンスを切り替えて戦うシャーマン"},
  {en:"Vi",jp:"ヴァイ",role:"JG",class:"ファイター",diff:2,style:"Qで突進してRで敵を吹き飛ばすパンチャー"},
  {en:"Viego",jp:"ヴィエゴ",role:"JG",class:"アサシン/ファイター",diff:3,style:"倒した敵に乗り移るキルリセットのルーインドキング"},
  {en:"Warwick",jp:"ウォリック",role:"JG",class:"ファイター/タンク",diff:1,style:"低HPの敵を本能的に追い詰める初心者向けオオカミ"},
  {en:"MonkeyKing",jp:"ウーコン",role:"JG",class:"ファイター/タンク",diff:2,style:"分身と棒術で敵を翻弄する孫悟空モチーフの戦士",img:"MonkeyKing"},
  {en:"XinZhao",jp:"ジン・ジャオ",role:"JG",class:"ファイター",diff:2,style:"3打目のノックアップとRで1vs多を制する槍使い",img:"XinZhao"},
  {en:"Zac",jp:"ザック",role:"JG",class:"タンク",diff:2,style:"弾力ある体で敵を弾き飛ばすスライムタンク"},
  {en:"Belveth",jp:"ベルヴェス",role:"JG",class:"ファイター",diff:3,style:"虚空の女王として素早い突進でDPSを維持するマンタ",img:"Belveth"},
  {en:"Lillia",jp:"リリア",role:"JG",class:"ファイター/メイジ",diff:3,style:"夢の花を咲かせながらスリープCCで集団戦を制圧する鹿"},
  {en:"Brand",jp:"ブランド (JG)",role:"JG",class:"メイジ",diff:2,style:"燃焼スタック爆発とバウンスRで集団戦を焼き尽くす"},

  // ===== MID (31) =====
  {en:"Ahri",jp:"アーリ",role:"MID",class:"メイジ/アサシン",diff:2,style:"チャームと霊火玉で翻弄するキツネの魔法使い"},
  {en:"Akali",jp:"アカリ",role:"MID",class:"アサシン",diff:3,style:"煙幕ステルスと五角形の急所を刺すアサシン"},
  {en:"Anivia",jp:"アニビア",role:"MID",class:"メイジ",diff:3,style:"蘇生卵と氷の壁で独自のゾーンを作る不死鳥"},
  {en:"Annie",jp:"アニー",role:"MID",class:"メイジ",diff:1,style:"ティバーズ召喚とスタンパッシブのシンプルなポイントアンドクリックメイジ"},
  {en:"AurelionSol",jp:"オーリオン・ソル",role:"MID",class:"メイジ",diff:3,style:"星を溜めて無限に成長する宇宙の竜",img:"AurelionSol"},
  {en:"Cassiopeia",jp:"カシオペア",role:"MID",class:"メイジ",diff:4,style:"猛毒とEの高速連打でDPSを維持する蛇女"},
  {en:"Corki",jp:"コーキ",role:"MID",class:"マークスマン/メイジ",diff:2,style:"ロケットとミサイルでAD/AP両方のダメージを出す"},
  {en:"Fizz",jp:"フィズ",role:"MID",class:"アサシン/ファイター",diff:3,style:"Eの無敵とRのサメで飛びかかる海のトリックスター"},
  {en:"Galio",jp:"ガリオ",role:"MID",class:"タンク/メイジ",diff:2,style:"グローバルRで味方を救いCCで敵を封じる石の巨人"},
  {en:"Leblanc",jp:"ルブラン",role:"MID",class:"アサシン/メイジ",diff:4,style:"分身と瞬間バーストで見た目を変えながら翻弄する魔法使い"},
  {en:"Lissandra",jp:"リサンドラ",role:"MID",class:"メイジ",diff:2,style:"氷のCC連打とR自己無敵で集団戦を支配する女王"},
  {en:"Lux",jp:"ラックス",role:"MID",class:"メイジ",diff:2,style:"長射程スキルで戦場を支配する光の魔法使い"},
  {en:"Malzahar",jp:"マルザハル",role:"MID",class:"メイジ/サポート",diff:2,style:"ヴォイドのビジョンで敵を縛り付けて集団戦を制する"},
  {en:"Orianna",jp:"オリアナ",role:"MID",class:"メイジ",diff:3,style:"時計仕掛けの玉を操る精密なゾーンコントロールメイジ"},
  {en:"Qiyana",jp:"キヤナ",role:"MID",class:"アサシン",diff:4,style:"元素の力を操り環境を武器にするアサシン"},
  {en:"Ryze",jp:"ライズ",role:"MID",class:"メイジ",diff:3,style:"ルーンと連続スキルでDPSを維持するマナ爆発メイジ"},
  {en:"Sylas",jp:"サイラス",role:"MID",class:"メイジ/ファイター",diff:3,style:"敵のウルトを盗んで使いこなす魔法の囚人"},
  {en:"Syndra",jp:"シンドラ",role:"MID",class:"メイジ",diff:3,style:"球を集めてRで瞬殺バーストを叩き込む暗い球使い"},
  {en:"Taliyah",jp:"タリヤ",role:"MID",class:"メイジ",diff:3,style:"石のサーフィンとRの岩の壁で地形を変えるメイジ"},
  {en:"Talon",jp:"タロン",role:"MID",class:"アサシン",diff:3,style:"壁を駆け上がって奇襲し後ろに羽根を残すアサシン"},
  {en:"TwistedFate",jp:"ツイステッドフェイト",role:"MID",class:"メイジ",diff:3,style:"グローバルRとカードCC選択で試合全体を動かすギャンブラー",img:"TwistedFate"},
  {en:"Veigar",jp:"ベイガー",role:"MID",class:"メイジ",diff:2,style:"AP永続スタックで際限なく成長する邪悪な小さなマスター"},
  {en:"Velkoz",jp:"ベル・コズ",role:"MID",class:"メイジ",diff:2,style:"直線スキルと分解ダメージでポークし続けるヴォイドの目",img:"Velkoz"},
  {en:"Vex",jp:"ヴェックス",role:"MID",class:"メイジ",diff:2,style:"影とビクビクのコンビでダッシュ全般を嫌うペシミスト"},
  {en:"Viktor",jp:"ビクター",role:"MID",class:"メイジ",diff:3,style:"アイテム強化でスキルをアップグレードするメカニクスの頂点"},
  {en:"Yasuo",jp:"ヤスオ",role:"MID",class:"ファイター/アサシン",diff:4,style:"疾風の刃と竜巻でノックアップ後にRを叩き込む剣士"},
  {en:"Zed",jp:"ゼド",role:"MID",class:"アサシン",diff:4,style:"影との入れ替えとR無敵でADCを瞬殺する暗器の主"},
  {en:"Zoe",jp:"ゾーイ",role:"MID",class:"メイジ",diff:4,style:"ポータルとスリープCCで夢の世界から一撃必殺する"},
  {en:"Zilean",jp:"ジリアン (MID)",role:"MID",class:"メイジ/サポート",diff:3,style:"時間爆弾スタンと蘇生Rで試合全体の時を司る"},
  {en:"Viego",jp:"ヴィエゴ (MID)",role:"MID",class:"アサシン/ファイター",diff:3,style:"倒した敵の体に乗り移るキルリセットのルーインドキング"},
  {en:"Akshan",jp:"アクシャン",role:"MID",class:"マークスマン/アサシン",diff:3,style:"テザーで壁を移動し倒された味方を復活させるヒーロー"},

  // ===== ADC (20) =====
  {en:"Aphelios",jp:"アフェリオス",role:"ADC",class:"マークスマン",diff:5,style:"5種の武器を切り替える極限の高スキルキャップADC"},
  {en:"Ashe",jp:"アッシュ",role:"ADC",class:"マークスマン",diff:1,style:"スロウとグローバルスタンRで味方を支援する弓の女王"},
  {en:"Caitlyn",jp:"ケイトリン",role:"ADC",class:"マークスマン",diff:2,style:"長射程とトラップでゾーンを支配する狙撃の名手"},
  {en:"Draven",jp:"ドレイヴン",role:"ADC",class:"マークスマン",diff:3,style:"回転する斧をキャッチしてスタックを積む高火力ADC"},
  {en:"Ezreal",jp:"エズリアル",role:"ADC",class:"マークスマン",diff:3,style:"E瞬間移動とスキルショットで機動的に戦うイクサー"},
  {en:"Jinx",jp:"ジンクス",role:"ADC",class:"マークスマン",diff:2,style:"武器切り替えとキルリセットRで後半無限加速するクレイジー"},
  {en:"Kaisa",jp:"カイ・サ",role:"ADC",class:"マークスマン/アサシン",diff:3,style:"ボイドスーツ進化とステルスダッシュで戦うハイブリッドADC",img:"Kaisa"},
  {en:"Kalista",jp:"カリスタ",role:"ADC",class:"マークスマン",diff:4,style:"矢を刺してホップし続ける超高機動のマークスマン"},
  {en:"KogMaw",jp:"コグ・マウ",role:"ADC",class:"マークスマン/メイジ",diff:2,style:"腐食液で防御を溶かしW強化で超長射程攻撃するヴォイド犬",img:"KogMaw"},
  {en:"Lucian",jp:"ルシアン",role:"ADC",class:"マークスマン",diff:3,style:"二連撃パッシブとダッシュを軸に動き回る高機動ガンスリンガー"},
  {en:"MissFortune",jp:"ミス・フォーチュン",role:"ADC",class:"マークスマン",diff:1,style:"バウンスAAとRの弾幕で初心者でも結果を出せるADC",img:"MissFortune"},
  {en:"Samira",jp:"サミーラ",role:"ADC",class:"マークスマン/ファイター",diff:4,style:"スタイルランクSでRが解放される無双系ガンブレードADC"},
  {en:"Senna",jp:"セナ",role:"ADC",class:"マークスマン/サポート",diff:3,style:"魂を集めて無限成長するADC/サポート兼用チャンピオン"},
  {en:"Sivir",jp:"シヴィア",role:"ADC",class:"マークスマン",diff:2,style:"ブーメランとリコシェとスペルシールドを持つ万能ADC"},
  {en:"Tristana",jp:"トリスターナ",role:"ADC",class:"マークスマン",diff:2,style:"レベルで射程が伸び続けるW爆弾ADC"},
  {en:"Twitch",jp:"トウィッチ",role:"ADC",class:"マークスマン/アサシン",diff:3,style:"ステルスから急襲し毒スタックで爆発ダメージを与えるネズミ"},
  {en:"Varus",jp:"ヴァルス",role:"ADC",class:"マークスマン/メイジ",diff:2,style:"チャージ長射程とスネアRでポーク特化のスナイパー"},
  {en:"Vayne",jp:"ヴェイン",role:"ADC",class:"マークスマン/アサシン",diff:4,style:"シルバーボルト3スタックで対タンク最強のナイトハンター"},
  {en:"Xayah",jp:"ザヤ",role:"ADC",class:"マークスマン",diff:3,style:"羽根を置いてEで引き戻すルートCCを持つ羽根のADC"},
  {en:"Zeri",jp:"ゼリ",role:"ADC",class:"マークスマン",diff:4,style:"Qが通常攻撃代わりでEで壁を越える高機動電気ADC"},

  // ===== SUPPORT (25) =====
  {en:"Alistar",jp:"アリスター",role:"SUPPORT",class:"タンク/ファイター",diff:3,style:"W→Qコンボ+タワーダイブ無敵Rで捕まえて離さない牛"},
  {en:"Bard",jp:"バード",role:"SUPPORT",class:"メイジ/キャッチャー",diff:5,style:"チャイムを集めながら壁トンネルと全体フリーズRで戦局を操る"},
  {en:"Blitzcrank",jp:"ブリッツクランク",role:"SUPPORT",class:"タンク/ファイター",diff:3,style:"ロケットグラブで孤立した敵を引き込む鉄の巨人"},
  {en:"Brand",jp:"ブランド (SUP)",role:"SUPPORT",class:"メイジ",diff:3,style:"燃焼3スタック爆発とバウンスRで高ダメージを出すキャリーサポート"},
  {en:"Janna",jp:"ジャンナ",role:"SUPPORT",class:"エンチャンター",diff:3,style:"シールドとRノックバックで敵のエンゲージを完全無力化"},
  {en:"Karma",jp:"カルマ",role:"SUPPORT",class:"エンチャンター/メイジ",diff:3,style:"マントラでQ/W/Eを強化し状況に応じて使い分ける万能サポート"},
  {en:"Leona",jp:"レオナ",role:"SUPPORT",class:"タンク",diff:2,style:"E突進→Qスタン+広範囲Rで確実にキルを作るタンクサポート"},
  {en:"Lulu",jp:"ルル",role:"SUPPORT",class:"エンチャンター",diff:3,style:"RノックアップとWポリモーフで味方を守り敵を変身させる妖精"},
  {en:"Maokai",jp:"マオカイ",role:"SUPPORT",class:"タンク/メイジ",diff:2,style:"Wルートと苗木ゾーンでフロントラインを維持する悲しい木"},
  {en:"Morgana",jp:"モルガナ",role:"SUPPORT",class:"メイジ/サポート",diff:2,style:"3秒ルートとEブラックシールドで敵を完全に封じる翼の女神"},
  {en:"Nami",jp:"ナミ",role:"SUPPORT",class:"エンチャンター/キャッチャー",diff:3,style:"バブルスタンとバウンスヒールとRノックアップで攻守両立"},
  {en:"Nautilus",jp:"ノーチラス",role:"SUPPORT",class:"タンク/ファイター",diff:2,style:"フック+パッシブ+E+Rの4種CC連打で一度捕まえたら逃げられない"},
  {en:"Pyke",jp:"パイク",role:"SUPPORT",class:"アサシン/ファイター",diff:4,style:"ステルス奇襲とR処刑でチーム全員にゴールドを配るアサシンサポート"},
  {en:"Rakan",jp:"ラカン",role:"SUPPORT",class:"エンチャンター/キャッチャー",diff:4,style:"跳び回りながらWノックアップとRチャームで集団戦を制する鳥人"},
  {en:"Rell",jp:"レル",role:"SUPPORT",class:"タンク",diff:4,style:"馬に乗り降りしながら飛び込み磁力でタンクする騎士サポート"},
  {en:"Renata",jp:"レナタ・グラスク",role:"SUPPORT",class:"エンチャンター/キャッチャー",diff:3,style:"バイアウト蘇生と敵を操る混乱Rで戦局を逆転させる",img:"Renata"},
  {en:"Seraphine",jp:"セラフィン",role:"SUPPORT",class:"エンチャンター/メイジ",diff:3,style:"音楽でチームをバフし超長距離RチャームでCC制圧する歌姫"},
  {en:"Sona",jp:"ソナ",role:"SUPPORT",class:"エンチャンター",diff:2,style:"Q/W/Eのオーラとパッシブ強化AAとRスタンで初心者でも貢献できる"},
  {en:"Soraka",jp:"ソラカ",role:"SUPPORT",class:"エンチャンター",diff:2,style:"単体大量ヒールとグローバルRで味方を生かし続ける純粋ヒーラー"},
  {en:"Swain",jp:"スウェイン (SUP)",role:"SUPPORT",class:"メイジ/ウォーロック",diff:3,style:"Eルート引き寄せとR吸収フィールドで積極的に前に出るメイジサポート"},
  {en:"Taric",jp:"タリック",role:"SUPPORT",class:"タンク/エンチャンター",diff:4,style:"Wリンクと遅延スタンE、全体無敵Rで集団戦を支配するタンクエンチャンター"},
  {en:"Thresh",jp:"スレッシュ",role:"SUPPORT",class:"タンク/キャッチャー",diff:4,style:"フックとランタン転送、フレイのノックバックと壁Rで全てをこなすキャッチャー"},
  {en:"Yuumi",jp:"ユーミ",role:"SUPPORT",class:"エンチャンター",diff:3,style:"味方に乗って完全無敵を維持しながらヒールとR波ルートを行う猫"},
  {en:"Zilean",jp:"ジリアン (SUP)",role:"SUPPORT",class:"メイジ/サポート",diff:3,style:"Q→W→Qのスタンコンボと蘇生RでADCを絶対に死なせない"},
  {en:"Zyra",jp:"ザイラ",role:"SUPPORT",class:"メイジ/キャッチャー",diff:3,style:"植物ゾーンとEルートRノックアップで戦域を支配するプラントサポート"},
];

// Role display config
const ROLE_CONFIG = {
  ALL:     { label: "全て", icon: "🎮", color: "#C89B3C" },
  TOP:     { label: "トップ", icon: "🛡️", color: "#4ade80" },
  JG:      { label: "ジャングル", icon: "🌲", color: "#c084fc" },
  MID:     { label: "ミッド", icon: "✨", color: "#60a5fa" },
  ADC:     { label: "ADC", icon: "🏹", color: "#f87171" },
  SUPPORT: { label: "サポート", icon: "💛", color: "#facc15" },
};

// Difficulty star display
function diffStars(n) {
  return '★'.repeat(n) + '☆'.repeat(5 - n);
}

// DDragon image URL
function splashUrl(c) {
  const key = c.img || c.en;
  return `https://ddragon.leagueoflegends.com/cdn/img/champion/splash/${key}_0.jpg`;
}
function squareUrl(c) {
  const key = c.img || c.en;
  return `https://ddragon.leagueoflegends.com/cdn/14.1.1/img/champion/${key}.png`;
}
